Création de la base de donnée pour le projet migrants

# Code de préparation des données pour projet 1 INSEE (innatio)
05/12/2025 - Master 2 SPE La Rochelle - UE Data to Information.
Auteur : Julia Mourgues
Crée la table `INAT_NAT_EPCI_REGION`, sérialisée en fichier CSV importée plus tard dans la table du même nom en BDD.

1. Importation des données

In [87]:
#Chargement des codes EPCI et départements
import pandas as pd
cols= ['EPCI', 'DEP']
EPCI= pd.read_excel(r"C:\Users\julia\OneDrive\Documents\Python_mineure_M2\HTML\projet\EPCI.xlsx", usecols=cols)
EPCI.head()

        EPCI DEP
0  200069193  01
1  240100883  01
2  240100883  01
3  200042497  01
4  200040350  01

In [88]:
EPCI= EPCI.rename(columns={"DEP":"num_dep"})
EPCI.head()

        EPCI num_dep
0  200069193      01
1  240100883      01
2  240100883      01
3  200042497      01
4  200040350      01

In [89]:
dpt_region = pd.read_csv(r"C:\Users\julia\OneDrive\Documents\Python_mineure_M2\HTML\projet\departements-region.csv",
    sep=",", encoding='UTF-8')

dpt_region.head()

  num_dep                 dep_name                 region_name
0      01                      Ain        Auvergne-Rhône-Alpes
1      02                    Aisne             Hauts-de-France
2      03                   Allier        Auvergne-Rhône-Alpes
3      04  Alpes-de-Haute-Provence  Provence-Alpes-Côte d'Azur
4      05             Hautes-Alpes  Provence-Alpes-Côte d'Azur

In [102]:
region_EPCI= EPCI.merge(dpt_region, left_on ="num_dep", right_on="num_dep", how="left")
region_EPCI["EPCI"] = region_EPCI["EPCI"].astype(str)
region_EPCI.head()

        EPCI num_dep dep_name           region_name
0  200069193      01      Ain  Auvergne-Rhône-Alpes
1  240100883      01      Ain  Auvergne-Rhône-Alpes
2  240100883      01      Ain  Auvergne-Rhône-Alpes
3  200042497      01      Ain  Auvergne-Rhône-Alpes
4  200040350      01      Ain  Auvergne-Rhône-Alpes

In [103]:
#Supprimer les doublons dans region_EPCI
region_EPCI = region_EPCI.drop_duplicates(subset="EPCI")

## Attention : il y a des EPCI à cheval sur deux régions. Donc là vous les supprimez !

In [104]:
INAT_NAT = pd.read_csv(
    r"C:\Users\julia\OneDrive\Documents\Python_mineure_M2\HTML\projet\_INAT_NAT_EPCI_2025-09-15.csv",
    sep=";",
    encoding='latin1',
    dtype={"unit": str}  
)

In [105]:
NAT_EPCI = pd.read_csv(
    r"C:\Users\julia\OneDrive\Documents\Python_mineure_M2\HTML\projet\_NAT_EPCI_2025-09-15.csv",
    sep=";",
    encoding='latin1',
    dtype={"unit": str}  # remplace "EPCI" par le nom exact de ta colonne
)

In [106]:
#renomer la colonne "unit" de Inat_Nat en "EPCI"
INAT_NAT= INAT_NAT.rename(columns={"unit":"EPCI"})
INAT_NAT["EPCI"] = INAT_NAT["EPCI"].astype(str)
INAT_NAT.head()

        EPCI  INAT_BIS           NAT_rec3  total_s
0  200023307  Etranger            Afghans      NaN
1  200023307  Etranger           Albanais      NaN
2  200023307  Etranger          Algériens    146.0
3  200023307  Etranger          Allemands      NaN
4  200023307  Etranger  Américains (U.S.)      NaN

In [107]:
#renomer la colonne "unit" de NAT_EPCI en "EPCI"
NAT_EPCI= NAT_EPCI.rename(columns={"unit":"EPCI"})
NAT_EPCI["EPCI"] = NAT_EPCI["EPCI"].astype(str)
NAT_EPCI.head()

        EPCI           NAT_rec3  total_s
0  200023307            Afghans      NaN
1  200023307           Albanais      NaN
2  200023307          Algériens    450.0
3  200023307          Allemands     30.0
4  200023307  Américains (U.S.)      NaN

In [115]:
#Réaliser une jointure pour ajouter les départements et régions aux données INAT_NAT sur la variable EPCI
INAT_NAT_REGION= INAT_NAT.merge(region_EPCI, left_on ="EPCI", right_on="EPCI", how="left")
INAT_NAT_REGION.head()

,EPCI,INAT_BIS,NAT_rec3,total_s,num_dep,dep_name,region_name
0,200023307,Etranger,Afghans,NaN,47,Lot-et-Garonne,Nouvelle-Aquitaine
1,200023307,Etranger,Albanais,NaN,47,Lot-et-Garonne,Nouvelle-Aquitaine
2,200023307,Etranger,Algériens,146.0,47,Lot-et-Garonne,Nouvelle-Aquitaine
3,200023307,Etranger,Allemands,NaN,47,Lot-et-Garonne,Nouvelle-Aquitaine
4,200023307,Etranger,Américains (U.S.),NaN,47,Lot-et-Garonne,Nouvelle-Aquitaine

In [119]:
#enregistrer les nouvelles bases de données avec les régions et départements
INAT_NAT_REGION.to_csv(r"C:\Users\julia\OneDrive\Documents\Python_mineure_M2\HTML\projet\INAT_NAT_EPCI_REGION.csv", index=False, sep=';',na_rep="NA" )

In [111]:
NAT_EPCI_REGION= NAT_EPCI.merge(region_EPCI, left_on ="EPCI", right_on="EPCI", how="left")
NAT_EPCI.head()

,EPCI,NAT_rec3,total_s,num_dep,dep_name,region_name
0,200023307,Afghans,NaN,47,Lot-et-Garonne,Nouvelle-Aquitaine
1,200023307,Albanais,NaN,47,Lot-et-Garonne,Nouvelle-Aquitaine
2,200023307,Algériens,450.0,47,Lot-et-Garonne,Nouvelle-Aquitaine
3,200023307,Allemands,30.0,47,Lot-et-Garonne,Nouvelle-Aquitaine
4,200023307,Américains (U.S.),NaN,47,Lot-et-Garonne,Nouvelle-Aquitaine

In [120]:
#enrichir NAT_EPCI_REGION  avec les informations de département et région
NAT_EPCI_REGION.to_csv(r"C:\Users\julia\OneDrive\Documents\Python_mineure_M2\HTML\projet\NAT_EPCI_REGION.csv", index=False, sep=';', na_rep="NA")

## Suite codée en SQL 
Aurélie HENRY

-- Voilà le SQL (de mémoire) qui a permis de jointer le csv de data.gouv téléchargé dans DBeaver avec le fichier inat_nat... 
-- avec la clé SIREN/EPCI pour ajouter la colonne nom dans inat_nat...

```SQL
update inat_nat_epci_region
set SIREN = e.SIREN, nom =e.nom from EPCI_name e
where inat_nat_epci_region.EPCI = e.SIREN;
```