# Code de préparation des données
Christine Plumejeaud-Perreau, UMR 7301 Migrinter

In [1]:
import pandas as pd
import geopandas as gpd
import json
from shapely.geometry import shape
import folium
from sqlalchemy import create_engine
import logging
import os
import pandas.io.sql as sql
from sqlalchemy import create_engine
pd.options.mode.chained_assignment = None  # default='warn'

import os
os.chdir('C:\Travail\Enseignement\Cours_M2_python\\2025\Projet_INSEE\Insee')

## Lire les shapefile EPCI et région 

Calculer la région d'appartenance des EPCI (par le centroid)

Données 2023 téléchargées depuis IGN ADMIN EXPRESS et rangées dans D:\Data\IMHANA\data\IGN_ADMIN_EXPRESS\ADMIN-EXPRESS-COG-CARTO_3-2__SHP_LAMB93_FXX_2023-05-03

- EPCI : "D:\Data\IMHANA\data\IGN_ADMIN_EXPRESS\ADMIN-EXPRESS-COG-CARTO_3-2__SHP_LAMB93_FXX_2023-05-03\ADMIN-EXPRESS-COG-CARTO\1_DONNEES_LIVRAISON_2023-05-03\ADECOGC_3-2_SHP_LAMB93_FXX\EPCI.shp"
- REGION : 
"D:\Data\IMHANA\data\IGN_ADMIN_EXPRESS\ADMIN-EXPRESS-COG-CARTO_3-2__SHP_LAMB93_FXX_2023-05-03\ADMIN-EXPRESS-COG-CARTO\1_DONNEES_LIVRAISON_2023-05-03\ADECOGC_3-2_SHP_LAMB93_FXX\REGION.shp"

In [13]:


EPCI_file = r"D:\Data\IMHANA\data\IGN_ADMIN_EXPRESS\ADMIN-EXPRESS-COG-CARTO_3-2__SHP_LAMB93_FXX_2023-05-03\ADMIN-EXPRESS-COG-CARTO\1_DONNEES_LIVRAISON_2023-05-03\ADECOGC_3-2_SHP_LAMB93_FXX\EPCI.shp"
REGION_file = r"D:\Data\IMHANA\data\IGN_ADMIN_EXPRESS\ADMIN-EXPRESS-COG-CARTO_3-2__SHP_LAMB93_FXX_2023-05-03\ADMIN-EXPRESS-COG-CARTO\1_DONNEES_LIVRAISON_2023-05-03\ADECOGC_3-2_SHP_LAMB93_FXX\REGION.shp"

In [14]:
epci = gpd.read_file(EPCI_file) #, where="CODE_SIREN IN ('200040244')"

In [ ]:
print(epci.shape) #1243, 5
print(epci.columns) #['ID', 'CODE_SIREN', 'NOM', 'NATURE', 'geometry']
epci.head()

(1243, 5)
Index(['ID', 'CODE_SIREN', 'NOM', 'NATURE', 'geometry'], dtype='object')

,ID,CODE_SIREN,NOM,NATURE,geometry
0,EPCI____0000002150236155,200041572,CC Dronne et Belle,Communauté de communes,"POLYGON ((514682.300 6464946.300, 514659.400 6..."
1,EPCI____0000002150237024,200090751,CA Grand Calais Terres et Mers,Communauté d'agglomération,"POLYGON ((613206.700 7085833.700, 613102.800 7..."
2,EPCI____0000002150236424,200068914,CC La Rochefoucauld porte du Périgord,Communauté de communes,"POLYGON ((510085.000 6506674.000, 510079.900 6..."
3,EPCI____0000002150235991,200026573,CC Haut-Jura Saint-Claude,Communauté de communes,"POLYGON ((917644.400 6577442.900, 917289.800 6..."
4,EPCI____0000002150236297,200066793,CA du Grand Annecy,Communauté d'agglomération,"POLYGON ((940784.000 6519645.300, 940832.400 6..."

In [20]:
epci.geometry.centroid

0    POINT (429551.659 6645721.960)
dtype: geometry

In [15]:
region = gpd.read_file(REGION_file)

In [ ]:
test = region.overlay(epci, how='intersection', keep_geom_type=False)
test

### Calculer l'intersection entre le centre des EPCI et les régions

In [ ]:
#region.within(epci.geometry.centroid)
#epci.geometry.centroid.within(region.geometry)

epci_points = epci.copy()
epci_points.geometry = epci_points.geometry.centroid

#region.overlay(epci_points, how='intersection', keep_geom_type=False)
epci_points = epci_points.overlay(region, how='intersection', keep_geom_type=False)

pd.unique(epci_points.INSEE_REG) #['75', '32', '27', '84', '44', '93', '76', '52', '24', '28', '11', '94', '53']

array(['75', '32', '27', '84', '44', '93', '76', '52', '24', '28', '11',
       '94', '53'], dtype=object)

In [17]:
pd.unique(epci_points.NOM_2)
print(epci_points.shape) #(1242, 9)

#epci_points[epci_points.CODE_SIREN == '200041572']
#epci_points = epci_points.rename_axis(columns={'NOM_2': 'NOM_REGION'}, inplace=True)    
#epci_points = epci_points.rename_axis(columns={'NOM_M': 'NOM_REGION_MAJ'}, inplace=True)    
epci_points.drop(columns=['ID_1', 'NOM_1', 'NATURE', 'ID_2', 'geometry'], inplace=True)

(1242, 9)

In [18]:
epci_points.head()

  CODE_SIREN               NOM_M               NOM_2 INSEE_REG
0  200041572  NOUVELLE-AQUITAINE  Nouvelle-Aquitaine        75
1  200068914  NOUVELLE-AQUITAINE  Nouvelle-Aquitaine        75
2  200041150  NOUVELLE-AQUITAINE  Nouvelle-Aquitaine        75
3  200041689  NOUVELLE-AQUITAINE  Nouvelle-Aquitaine        75
4  200041614  NOUVELLE-AQUITAINE  Nouvelle-Aquitaine        75

In [19]:
# for siren in epci.CODE_SIREN:
#     if siren not in epci_points.CODE_SIREN:
#         print(f"SIREN {siren} is missing in epci_points")
#epci.CODE_SIREN not in epci_points.CODE_SIREN

#SIREN 200041572 is missing in epci_points
#data = data.reset_index()
#data = data.query("IMMI==1").join(data.query("IMMI==2")[['CANTVILLE', 'total']].set_index('CANTVILLE'), on='CANTVILLE', lsuffix='_immigres', rsuffix='_nonImmigres')
#data['part_immigre'] = 100 * data.total_immigres / (data.total_immigres + data.total_nonImmigres)

test = epci.join(epci_points.set_index('CODE_SIREN'), on='CODE_SIREN', how='outer', rsuffix='_points')
print(test.shape)
#1243 rows, 13 columns
test[(test.CODE_SIREN).isna()]
region[region.INSEE_REG == '85']
test[(test.INSEE_REG).isna()] #248500191 CC de l'Île de Noirmoutier pour

(1243, 8)

,ID,CODE_SIREN,NOM,NATURE,geometry,NOM_M,NOM_2,INSEE_REG
103,EPCI____0000002150237161,248500191,CC de l'Île de Noirmoutier,Communauté de communes,"MULTIPOLYGON (((305832.500 6664166.500, 306062...",NaN,NaN,NaN

In [89]:
region[region.NOM == 'Pays de la Loire']

,ID,NOM_M,NOM,INSEE_REG,geometry
6,REGION_FXX_0000000000007,PAYS DE LA LOIRE,Pays de la Loire,52,"MULTIPOLYGON (((293225.000 6674149.200, 293233..."

In [20]:
print(test[(test.INSEE_REG).isna()]) #248500191 CC de l'Île de Noirmoutier pour region[region.INSEE_REG == '85']

test.loc[test['CODE_SIREN']=='248500191', 'NOM_2'] = 'Pays de la Loire'
test.loc[test['CODE_SIREN']=='248500191', 'NOM_M'] = 'PAYS DE LA LOIRE'
test.loc[test['CODE_SIREN']=='248500191', 'INSEE_REG'] = '52'

#test[test.INSEE_REG.isna()]['NOM_M'] = 'PAYS DE LA LOIRE'
print(test[(test.INSEE_REG).isna()])
test[test['CODE_SIREN']=='248500191']

                           ID CODE_SIREN                         NOM  \
103  EPCI____0000002150237161  248500191  CC de l'Île de Noirmoutier

                     NATURE  \
103  Communauté de communes

                                              geometry NOM_M NOM_2 INSEE_REG
103  MULTIPOLYGON (((305832.500 6664166.500, 306062...   NaN   NaN       NaN
Empty GeoDataFrame
Columns: [ID, CODE_SIREN, NOM, NATURE, geometry, NOM_M, NOM_2, INSEE_REG]
Index: []

,ID,CODE_SIREN,NOM,NATURE,geometry,NOM_M,NOM_2,INSEE_REG
103,EPCI____0000002150237161,248500191,CC de l'Île de Noirmoutier,Communauté de communes,"MULTIPOLYGON (((305832.500 6664166.500, 306062...",PAYS DE LA LOIRE,Pays de la Loire,52

In [22]:
test.drop([ 'ID'], axis=1, inplace=True)

### Sauvegarde du fichier epci enrichi avec les régions

In [23]:
print(test.columns) #CODE_SIREN	NOM	NATURE	geometry	NOM_M	NOM_2	INSEE_REG
print(test.shape)
#test.to_file('epci_regions_metropole_L93_2154.gpkg', index=False, driver="GPKG")

Index(['CODE_SIREN', 'NOM', 'NATURE', 'geometry', 'NOM_M', 'NOM_2',
       'INSEE_REG'],
      dtype='object')
(1243, 7)

In [24]:
epci = gpd.read_file('epci_regions_metropole_L93_2154.gpkg')

epci.head()

,CODE_SIREN,NOM,NATURE,NOM_M,NOM_2,INSEE_REG,geometry
0,200041572,CC Dronne et Belle,Communauté de communes,NOUVELLE-AQUITAINE,Nouvelle-Aquitaine,75,"POLYGON ((514682.300 6464946.300, 514659.400 6..."
1,200090751,CA Grand Calais Terres et Mers,Communauté d'agglomération,HAUTS-DE-FRANCE,Hauts-de-France,32,"POLYGON ((613206.700 7085833.700, 613102.800 7..."
2,200068914,CC La Rochefoucauld porte du Périgord,Communauté de communes,NOUVELLE-AQUITAINE,Nouvelle-Aquitaine,75,"POLYGON ((510085.000 6506674.000, 510079.900 6..."
3,200026573,CC Haut-Jura Saint-Claude,Communauté de communes,BOURGOGNE-FRANCHE-COMTE,Bourgogne-Franche-Comté,27,"POLYGON ((917644.400 6577442.900, 917289.800 6..."
4,200066793,CA du Grand Annecy,Communauté d'agglomération,AUVERGNE-RHONE-ALPES,Auvergne-Rhône-Alpes,84,"POLYGON ((940784.000 6519645.300, 940832.400 6..."

In [ ]:
import pandas.io.sql as sql
from sqlalchemy import create_engine

epci = gpd.read_file('epci_regions_metropole_L93_2154.gpkg')

engine = create_engine('postgresql://postgres:postgres@localhost:5432/inseedb')
ORM_conn=engine.connect()

epci.to_postgis('geoepci', con=ORM_conn , schema='imhana2021', if_exists='replace', index=False)
#result.to_sql('INAT_NAT_EPCI', con=engine , schema='imhana2021', if_exists='replace', index=False)

ORM_conn.commit()
ORM_conn.close()

## Lire les données NAT2 pour calculer par EPCI 

Nationalités spéciales présentes dans NAT2: 
- *Tous* : population totale
- *immigres* : population immigree  (née étranger à l'étranger )
- *francaisParAcquisition* : pop. naturalisée français par acquisition
- *etrangers*: pop. étrangère

datapath = "C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\2026.01.22\EPCI\"
Suffix = "_2026.01.22.csv"
- NAT_EPCI_2026.01.22.csv

- INAT_NAT_EPCI_2026.01.22.csv

- GEN2_NAT_EPCI_2026.01.22.csv

- IMMI_NAT_EPCI_2026.01.22.csv

ou "C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD\2026-01-27\2026.01.22\EPCI\_NAT_EPCI_2026.01.22.csv"
(non, ca ne change rien au niveau des doublons)

Les **epci du grand paris** : 
200057867	Plaine Commune	9
200057875	Est Ensemble	9
200057941	Paris Est Marne et Bois	13
200057966	Vallée Sud-Grand Paris	11
200057974	Grand Paris Seine Ouest	8
200057982	Paris Ouest La Défense	11
200057990	Boucle Nord de Seine	7
200058006	Grand Paris Sud Est Avenir	16
200058014	Grand-Orly Seine Bièvre	24
200058097	Paris Terres d'Envol	8
200058790	Grand Paris Grand Est	14

font partie de **l'epci 200054781 Métropole du Grand Paris** bien présente dans l'export comme 248500191    (Ile de Noirmoutiers)

In [57]:
datapath = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\\"
suffix = "_2026.01.22.csv"
epcisuffix = "_EPCI_2026.01.22.csv"
# - NAT_EPCI_2026.01.22.csv
# - INAT_NAT_EPCI_2026.01.22.csv
# - GEN2_NAT_EPCI_2026.01.22.csv
# - IMMI_NAT_EPCI_2026.01.22.csv


nat_epci_file = datapath+"NAT_EPCI"+suffix
#nat_epci_file = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\NAT_EPCI_2026.01.22.csv"

demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')

In [52]:
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)

datapath = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\\"
suffix = "_2026.01.22.csv"

EPT_Paris = ['200057867','200057875','200057941','200057966','200057974','200057982','200057990','200058006','200058014','200058097','200058790']
EPCI_fictives = ['HORS__GFP', 'RESTANT__GFP', 'fictive_200027399', 'fictive_242320034', 'fictive_242320059', 'fictive_244701389']

nationalites_speciales = ['Tous', 'etrangers', 'francaisParAcquisition', 'immigres']
liste_natio = pd.read_csv('liste_nationalites.csv')['nationalites'].tolist()

doublons_CC_EPCI = pd.read_csv('doublons_CC_EPCI.csv', sep=';', encoding='utf-8', dtype={'doublons_CC_EPCI':str})['doublons_CC_EPCI'].tolist()
doublons_CA_CU_EPCI = pd.read_csv('doublons_CA_CU_EPCI.csv', sep=';', encoding='utf-8', dtype={'doublons_CA_CU_EPCI':str})['doublons_CA_CU_EPCI'].tolist()

print(doublons_CC_EPCI)
print(doublons_CA_CU_EPCI)

STRANGERS = ['Etranger', 'Français par acquisition']
FRENCH_DOMTOM = pd.read_csv('FRENCH_DOMTOM.csv', sep=';', encoding='utf-8', dtype={'FRENCH_DOMTOM':str})['FRENCH_DOMTOM'].tolist()
#FRENCH_DOMTOM = demographie_etrangers.query("INAT_BIS.str.startswith('Français') and INAT_BIS != 'Français par acquisition'").INAT_BIS.unique()
print(FRENCH_DOMTOM)

#epci = gpd.read_file('epci_regions_metropole_L93_2154.gpkg')
epci = gpd.read_file('epci_with_demo_metropole2154_.gpkg')

['200072106', '200066462', '200071033', '200071884', '200068088', '200072676', '246401756', '248400335', '200035723', '200030435', '200035129', '200067668', '248200016', '200070332', '247800550', '200068765', '200069722', '200071140', '200070308']
['200040277', '243500741', '244400610', '248400251', '246100663', '200040681', '247600588']
['Français Guadeloupe (971)', 'Français Guyane (973)', 'Français La Réunion (974)', 'Français Martinique (972)', 'Français Mayotte (976)', 'Français Metropole', 'Français Nouvelle-Calédonie (988)', 'Français Polynésie Française (987)', 'Français Saint-Martin (978)', 'Français Saint-Pierre-et-Miquelon (975)', 'Français Wallis et Futuna (986)', 'Français Saint-Barthélemy (977)']

In [26]:
pd.unique(demographie_etrangers.unit).size
#1230

1230

In [9]:
demographie_etrangers[demographie_etrangers.unit == '200057867']

Empty DataFrame
Columns: [unit, NAT2, total_s, NOM]
Index: []

### Calcul d'un bilan sur l'alignement au niveau de la jointure

- Les epci_fictives (demographie) n'auront pas de géométrie
- RESTANT_GFP et HORS_GFP non plus
- Les EPCI de moins de 5000 hab. faisant partie du RESTANT_GFP non plus

- Les ept de Métropole du Grand Paris n'ont pas de données de démographie. Il faut retirer leur géométrie, et n'utiliser que celle de 200054781	Métropole du Grand Paris qui a les données de déomgraphie

In [ ]:
demographie_etrangers.query("NAT2=='Tous'")[demographie_etrangers.unit == '200054781']
#200054781	Métropole du Grand Paris
demographie_etrangers.query("NAT2=='Tous'")[demographie_etrangers.unit == '200057867']
#200057867	Plaine Commune n'est pas dans les données de démographie

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_15660\3913963069.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  demographie_etrangers.query("NAT2=='Tous'")[demographie_etrangers.unit == '200054781']
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_15660\3913963069.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  demographie_etrangers.query("NAT2=='Tous'")[demographie_etrangers.unit == '200057867']

Empty DataFrame
Columns: [unit, NAT2, total_s, NOM]
Index: []

In [ ]:
epci.query("CODE_SIREN=='200054781'")
#OK Métropole du Grand Paris présente dans le shapefile
epci.query("CODE_SIREN=='200057867'")
#OK Plaine Commune	présente dans le shapefile, alors qu'elle appartient à Métropole du Grand Paris

,CODE_SIREN,NOM,NATURE,NOM_M,NOM_2,INSEE_REG,geometry
204,200057867,Plaine Commune,Etablissement public territorial,ILE-DE-FRANCE,Île-de-France,11,"POLYGON ((649704.700 6868446.600, 650150.000 6..."

In [131]:
test = epci.join(demographie_etrangers.set_index('unit').query("NAT2=='Tous'"), on='CODE_SIREN', how='outer', rsuffix='_demo')
print(test.shape) #(103241, 10)
#1243 rows, 13 columns
test[(test.CODE_SIREN.str.startswith('fictive_'))]

(1275, 10)

,CODE_SIREN,NOM,NATURE,NOM_M,NOM_2,INSEE_REG,geometry,NAT2,total_s,NOM_demo
NaN,fictive_200027399,NaN,NaN,NaN,NaN,NaN,None,Tous,17807.0,NaN
NaN,fictive_242320034,NaN,NaN,NaN,NaN,NaN,None,Tous,7090.0,NaN
NaN,fictive_242320059,NaN,NaN,NaN,NaN,NaN,None,Tous,10019.0,NaN
NaN,fictive_244701389,NaN,NaN,NaN,NaN,NaN,None,Tous,6801.0,NaN

In [140]:
bilan = test.loc[test.NOM_demo.isna()  , ['CODE_SIREN', 'NOM', 'INSEE_REG', 'NOM_2']].sort_values(by='CODE_SIREN')
bilan.to_csv('bilan_epci_SANS_demo.csv', index=False)

In [148]:
test = epci.join(demographie_etrangers.set_index('unit').query("NAT2=='Tous'"), on='CODE_SIREN', how='left', rsuffix='_demo')
print(test.shape) #(103241, 10)
#1243 rows, 13 columns
test[(test.CODE_SIREN.str.startswith('fictive_'))] #Rien, normal
test.loc[test.NOM_demo.isna()  , ['CODE_SIREN', 'NOM', 'INSEE_REG', 'NOM_2']].sort_values(by='CODE_SIREN')
# Suppression des EPT de la Métropole du Grand Paris, qui n'ont pas de données de démographie
test = test.query("INSEE_REG != '11' and NOM_demo.isna()")
#Conserver un shapefile des EPCI sans données de démographie, pour les analyser plus tard, et dont les données correspondent au RESTANT__GFP
epci_missing_demo = test.loc[test.NOM_demo.isna()  , ['CODE_SIREN', 'NOM', 'INSEE_REG', 'NOM_2', 'geometry']]
epci_missing_demo.to_file('epci_missing_demo.gpkg', index=False, driver="GPKG")
epci_missing_demo

(1269, 10)

,CODE_SIREN,NOM,INSEE_REG,NOM_2,geometry
231,244600573,CC du Causse de Labastide-Murat,76,Occitanie,"POLYGON ((586015.100 6384521.600, 586006.000 6..."
265,241501089,CC Cère et Goul en Carladès,84,Auvergne-Rhône-Alpes,"POLYGON ((670697.700 6419323.300, 670700.600 6..."
402,200007177,CC Pays de Nérondes,24,Centre-Val de Loire,"POLYGON ((683834.000 6641503.100, 683788.900 6..."
730,200071652,CC du Pays Fertois et du Bocage Carrougien,28,Normandie,"POLYGON ((474571.000 6832751.700, 474612.800 6..."
732,200072007,CC de la Montagne d'Ardèche,84,Auvergne-Rhône-Alpes,"POLYGON ((773321.700 6386283.400, 773303.500 6..."
1109,243600343,CC Cœur de Brenne,24,Centre-Val de Loire,"POLYGON ((567371.900 6621619.400, 567372.800 6..."
1135,245501176,CC du Territoire de Fresnes-en-Woëvre,44,Grand Est,"POLYGON ((900593.800 6887938.900, 900655.200 6..."
1178,200070910,CC Tille et Venelle,27,Bourgogne-Franche-Comté,"POLYGON ((848239.600 6723579.000, 848207.800 6..."

### Jointure finale entre les données de démographie et les données géographiques des EPCI

In [ ]:
#test = epci.join(demographie_etrangers.set_index('unit').query("NAT2=='Tous'"), on='CODE_SIREN', how='outer', rsuffix='_demo')

EPT_Paris = ['200057867','200057875','200057941','200057966','200057974','200057982','200057990','200058006','200058014','200058097','200058790']
EPCI_fictives = ['HORS__GFP', 'RESTANT__GFP', 'fictive_200027399', 'fictive_242320034', 'fictive_242320059', 'fictive_244701389']

nationalites_speciales = ['Tous', 'etrangers', 'francaisParAcquisition', 'immigres']
epci.query("CODE_SIREN not in @EPT_Paris")
demographie_etrangers.query("NAT2 in @nationalites_speciales and unit =='200054781'")

            unit                    NAT2  total_s                       NOM
18548  200054781                    Tous  7103801  Métropole du Grand Paris
18600  200054781                immigres  1655407  Métropole du Grand Paris
18652  200054781  francaisParAcquisition   732003  Métropole du Grand Paris
18704  200054781               etrangers  1235801  Métropole du Grand Paris

In [10]:
## Identifier les EPCI exportées en doublon
test = demographie_etrangers.query("NAT2 in @nationalites_speciales and not(unit in @EPCI_fictives)").pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="count")
test.rename_axis(columns=None, inplace=True)
test.reset_index(inplace=True)

print(test.columns)
type(test)
test.info #1224 rows × 6 columns
test.query("Tous !=1").sort_values(by='NOM').to_csv('bilan_demographie_doublons.csv', index=False) 

doublons = test.query("Tous !=1").sort_values(by='NOM') 
doublons

Index(['unit', 'NOM', 'Tous', 'etrangers', 'francaisParAcquisition',
       'immigres'],
      dtype='object')

,unit,NOM,Tous,etrangers,francaisParAcquisition,immigres
153,200040277,CA Agglo du Pays de Dreux,2,2,2,2
596,200071140,CA Moulins Communauté,2,2,2,2
540,200070308,CA Mâconnais Beaujolais Agglomération,2,2,2,2
906,243500741,CA Redon Agglomération,2,2,2,2
967,244400610,CA de la Presqu'île de Guérande Atlantique (Ca...,2,2,2,2
1182,248400251,CA du Grand Avignon (COGA),2,2,2,2
655,200072106,CC Adour Madiran,2,2,2,2
172,200040681,CC Enclave des Papes-Pays de Grignan,2,2,2,2
315,200066462,CC Interco Normandie Sud Eure,2,2,2,2
589,200071033,CC Jabron-Lure-Vançon-Durance,2,2,2,2
636,200071884,CC Le Grand Charolais,2,2,2,2
420,200068088,CC Les Bertranges,2,2,2,2
669,200072676,CC Maine Saosnois,2,2,2,2
1059,246401756,CC Pays de Nay,2,2,2,2
1186,248400335,CC Vaison Ventoux,2,2,2,2
104,200035723,CC Ventoux Sud,2,2,2,2
52,200030435,CC d'Aire-sur-l'Adour,2,2,2,2
93,200035129,CC de Cèze Cévennes,2,2,2,2
390,200067668,"CC de la Cléry, du Betz et de l'Ouanne",2,2,2,2
1169,248200016,CC des Deux Rives,2,2,2,2
543,200070332,CC des Savoir-Faire,2,2,2,2
1143,247600588,CC des Villes Sours,2,2,2,2
1157,247800550,CC du Pays Houdanais (CCPH),2,2,2,2
448,200068765,CC du Sisteronais-Buëch,2,2,2,2
513,200069722,CC interrégionale Aumale - Blangy-sur-Bresle,2,2,2,2
1048,246100663,CU d'Alençon,2,2,2,2

In [ ]:
# Ce sont des EPCI à cheval sur deux régions qui apparaissent en double compte dans mon export

#test.query("unit =='200070332'")
#.pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="sum")

## Si CC alors max, sinon sum, pour éviter les doublons
demographie_etrangers.query("NAT2 in @nationalites_speciales and unit =='200070332'").pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="max")

# https://fr.wikipedia.org/wiki/Communaut%C3%A9_de_communes_des_Savoir-Faire
# La Communauté de communes des Savoir-Faire est une communauté de communes française, située dans les départements de la Haute-Marne et de la Haute-Saône et la région Grand Est et Bourgogne Franche-Comté

demographie_etrangers.query("NAT2 in @nationalites_speciales and unit =='248400251'").pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="sum")
# Le Grand Avignon est une communauté d'agglomération française, située sur les départements de Vaucluse et du Gard en régions Provence-Alpes-Côte d'Azur et Occitanie, autour de la ville d'Avignon. 
# https://fr.wikipedia.org/wiki/Communaut%C3%A9_d%27agglom%C3%A9ration_du_Grand_Avignon

demographie_etrangers.query("NAT2 in @nationalites_speciales and unit =='200040277'").pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="sum")
# La communauté d'agglomération du Pays de Dreux est une communauté d'agglomération française qui occupe la partie eurélienne du Drouais et la partie nord du Thymerais. Son siège se situe dans le département d'Eure-et-Loir en région Centre-Val de Loire. Elle comporte néanmoins des communes du département de l'Eure (région Normandie). 
# https://fr.wikipedia.org/wiki/Communaut%C3%A9_d%27agglom%C3%A9ration_du_Pays_de_Dreux

demographie_etrangers.query("NAT2 in @nationalites_speciales and unit =='246100663'").pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="sum")

demographie_etrangers.query("NAT2 in @nationalites_speciales and unit =='246100663'").pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="sum")

demographie_etrangers.query("NAT2 in @nationalites_speciales and unit =='200035723'").pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="max")

demographie_etrangers.query("NAT2 in @nationalites_speciales and unit =='248200016'")
#.pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="max")
# La communauté de communes des Deux Rives est une communauté de communes française, située dans les départements de Tarn-et-Garonne, de Lot-et-Garonne et du Gers dans les régions Occitanie et Nouvelle-Aquitaine.

             unit                    NAT2  total_s                NOM
80827   248200016                    Tous    18357  CC des Deux Rives
80988   248200016                immigres     1544  CC des Deux Rives
81149   248200016  francaisParAcquisition      614  CC des Deux Rives
81310   248200016               etrangers     1215  CC des Deux Rives
102930  248200016                    Tous    18899  CC des Deux Rives
102951  248200016                immigres     1565  CC des Deux Rives
102972  248200016  francaisParAcquisition      626  CC des Deux Rives
102993  248200016               etrangers     1229  CC des Deux Rives

In [ ]:
doublons_CC_EPCI = doublons.query("NOM.str.startswith('CC')").unit.unique()
doublons_CC_EPCI = doublons_CC_EPCI.tolist()
doublons_CC_EPCI.remove('200040681') 
doublons_CC_EPCI.remove('247600588') 
doublons_CC_EPCI.append('200071140') 
doublons_CC_EPCI.append('200070308')

doublons_CA_CU_EPCI = doublons.query("not NOM.str.startswith('CC')").unit.unique()
doublons_CA_CU_EPCI = doublons_CA_CU_EPCI.tolist()
doublons_CA_CU_EPCI.append('200040681') 
doublons_CA_CU_EPCI.append('247600588') 
doublons_CA_CU_EPCI.remove('200071140') 
doublons_CA_CU_EPCI.remove('200070308') 
doublons_CA_CU_EPCI

df = pd.DataFrame({'doublons_CC_EPCI':doublons_CC_EPCI})
df.to_csv('doublons_CC_EPCI.csv', index=False)
df = pd.DataFrame({'doublons_CA_CU_EPCI':doublons_CA_CU_EPCI})
df.to_csv('doublons_CA_CU_EPCI.csv', index=False)

#### Calcul le plus important

In [5]:
demo01 = demographie_etrangers.query("NAT2 in @nationalites_speciales and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM'], columns='NAT2', values='total_s')
demo02 = demographie_etrangers.query("NAT2 in @nationalites_speciales and (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="max") 
demo03 = demographie_etrangers.query("NAT2 in @nationalites_speciales and (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="sum") 

frames = [demo01, demo02, demo03]

result = pd.concat(frames)
result

,NAT2,Tous,etrangers,francaisParAcquisition,immigres
unit,NOM,,,,
200000172,CC Faucigny-Glières,27764,2382,1789,3543
200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,36232,311,297,528
200000545,CC des Portes de Romilly-sur-Seine,18866,2065,1331,2787
200000628,CC Rhône Lez Provence,24003,1626,1236,2338
200000800,CC Cour de Sologne,10310,278,264,451
...,...,...,...,...,...
243500741,CA Redon Agglomération,66837,1261,659,1666
244400610,CA de la Presqu'île de Guérande Atlantique (Cap Atlantique),76565,850,910,1521
246100663,CU d'Alençon,55435,2801,1476,3727
247600588,CC des Villes Sours,35817,247,269,430
248400251,CA du Grand Avignon (COGA),194858,18851,12941,27168

#### Vérification des calculs

- demo02 : il faut prendre le max des doublons
- demo03 : il faut prendre la sum des doublons

In [289]:
demo02 = demographie_etrangers.query("NAT2 in @nationalites_speciales and (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="max") 

demo02.rename_axis(columns=None, inplace=True)
demo02.reset_index(inplace=True)
demo02[['unit', 'NOM', 'Tous']].sort_values(by='NOM')

         unit                                           NOM   Tous
11  200071140                         CA Moulins Communauté  64257
8   200070308         CA Mâconnais Beaujolais Agglomération  78980
13  200072106                              CC Adour Madiran  23955
3   200066462                 CC Interco Normandie Sud Eure  37618
10  200071033                 CC Jabron-Lure-Vançon-Durance   5328
12  200071884                         CC Le Grand Charolais  39682
5   200068088                             CC Les Bertranges  19700
14  200072676                             CC Maine Saosnois  27534
15  246401756                                CC Pays de Nay  28841
18  248400335                             CC Vaison Ventoux  16704
2   200035723                                CC Ventoux Sud   9556
0   200030435                         CC d'Aire-sur-l'Adour  12880
1   200035129                           CC de Cèze Cévennes  19197
4   200067668        CC de la Cléry, du Betz et de l'Ouanne  19986
17  248200016                             CC des Deux Rives  18899
9   200070332                           CC des Savoir-Faire  15082
16  247800550                   CC du Pays Houdanais (CCPH)  29988
6   200068765                       CC du Sisteronais-Buëch  25315
7   200069722  CC interrégionale Aumale - Blangy-sur-Bresle  21305

In [288]:
demo03 = demographie_etrangers.query("NAT2 in @nationalites_speciales and (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="sum") 
demo03.rename_axis(columns=None, inplace=True)
demo03.reset_index(inplace=True)
demo03[['unit', 'NOM', 'Tous']].sort_values(by='NOM')

        unit                                                NOM    Tous
0  200040277                          CA Agglo du Pays de Dreux  115490
2  243500741                             CA Redon Agglomération   66837
3  244400610  CA de la Presqu'île de Guérande Atlantique (Ca...   76565
6  248400251                         CA du Grand Avignon (COGA)  194858
1  200040681               CC Enclave des Papes-Pays de Grignan   22728
5  247600588                                CC des Villes Sours   35817
4  246100663                                       CU d'Alençon   55435

In [277]:
demographie_etrangers.query("NAT2 in @nationalites_speciales and (unit =='200068765') ")

             unit                    NAT2  total_s                      NOM
99947   200068765                    Tous    24962  CC du Sisteronais-Buëch
99999   200068765                immigres     1923  CC du Sisteronais-Buëch
100051  200068765  francaisParAcquisition      882  CC du Sisteronais-Buëch
100103  200068765               etrangers     1348  CC du Sisteronais-Buëch
102919  200068765                    Tous    25315  CC du Sisteronais-Buëch
102940  200068765                immigres     1944  CC du Sisteronais-Buëch
102961  200068765  francaisParAcquisition      888  CC du Sisteronais-Buëch
102982  200068765               etrangers     1364  CC du Sisteronais-Buëch

In [222]:
test = demographie_etrangers.query("NAT2 in @nationalites_speciales and unit =='200054781'").pivot(index=['unit', 'NOM'], columns='NAT2', values='total_s')
test.rename_axis(columns=None, inplace=True)
test.reset_index(inplace=True)

print(test.columns)
type(test)
test.info
test

Index(['unit', 'NOM', 'Tous', 'etrangers', 'francaisParAcquisition',
       'immigres'],
      dtype='object')

,unit,NOM,Tous,etrangers,francaisParAcquisition,immigres
0,200054781,Métropole du Grand Paris,7103801,1235801,732003,1655407

#### Petit bout de code pour faire du webscraping sur wikipedia

voir code dans C:\Travail\Enseignement\Cours_M2_python\2025\Projet_INSEE\Insee\extract_wikipedia.py

In [262]:
import requests
from bs4 import BeautifulSoup

HEADERS = {
    "User-Agent": "TestInfobox/1.0 (contact: email@example.com)"
}

url = "https://fr.wikipedia.org/wiki/Communaut%C3%A9_de_communes_Vaison_Ventoux"
html = requests.get(url, headers=HEADERS).text
soup = BeautifulSoup(html, "html.parser")

infobox = soup.select_one("table.infobox")

print(infobox is not None)

True

### Le résultat démographie, sans doublons, avec tous, immigrés, etrangers, etc.

In [6]:
result.rename_axis(columns=None, inplace=True)
result.reset_index(inplace=True)

print(result.columns)
print(result.shape) #(1224, 6)

result

Index(['unit', 'NOM', 'Tous', 'etrangers', 'francaisParAcquisition',
       'immigres'],
      dtype='object')
(1224, 6)

,unit,NOM,Tous,etrangers,francaisParAcquisition,immigres
0,200000172,CC Faucigny-Glières,27764,2382,1789,3543
1,200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,36232,311,297,528
2,200000545,CC des Portes de Romilly-sur-Seine,18866,2065,1331,2787
3,200000628,CC Rhône Lez Provence,24003,1626,1236,2338
4,200000800,CC Cour de Sologne,10310,278,264,451
...,...,...,...,...,...,...
1219,243500741,CA Redon Agglomération,66837,1261,659,1666
1220,244400610,CA de la Presqu'île de Guérande Atlantique (Ca...,76565,850,910,1521
1221,246100663,CU d'Alençon,55435,2801,1476,3727
1222,247600588,CC des Villes Sours,35817,247,269,430
1223,248400251,CA du Grand Avignon (COGA),194858,18851,12941,27168

### Sauver les epci avec les géometry et les comptes de population par nationalités spéciales (Tous, 'etrangers',	'francaisParAcquisition',	'immigres')

In [ ]:
#1224 + 11 ept de paris + 8 sans démographie car moins de 5000 hab = 1243, soit le nombre d'EPCI dans le shapefile, ce qui est cohérent

import pandas.io.sql as sql
from sqlalchemy import create_engine

epci_with_demo = epci.query("CODE_SIREN not in @EPT_Paris").join(result[['unit', 'Tous','etrangers',	'francaisParAcquisition',	'immigres']].set_index('unit'), on='CODE_SIREN', how='left', rsuffix='_demo')
#epci_with_demo.to_file('epci_with_demo_metropole2154_.gpkg', index=False, driver="GPKG")

epci_with_demo #1232 rows, 11 columns (un shapefile des EPCI de la métropole avec les données de démographie, à l'exception des 11 EPT de la Métropole du Grand Paris qui n'ont pas de données de démographie)

engine = create_engine('postgresql://postgres:postgres@localhost:5432/inseedb')
ORM_conn=engine.connect()

epci_with_demo.to_postgis('geoepci_demo', con=ORM_conn , schema='imhana2021', if_exists='replace', index=False)

ORM_conn.commit()
ORM_conn.close()

In [ ]:
len(demographie_etrangers.NAT2.unique()) #199 * 4 octets pour un int selon le type de données, soit 796 octets, ce qui est cohérent avec les 103241 lignes et 10 colonnes du test
liste_natio = demographie_etrangers.NAT2.unique()
liste_natio = liste_natio.tolist()
liste_natio.remove('Tous')
liste_natio.remove('etrangers')     
liste_natio.remove('francaisParAcquisition')     
liste_natio.remove('immigres')     
liste_natio

liste_nation_df = pd.DataFrame({'nationalites': liste_natio})
liste_nation_df.to_csv('liste_nationalites.csv', index=False)

### Calculer démographie sur toutes les nationalités

In [53]:

demo01 = demographie_etrangers.query(" not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM'], columns='NAT2', values='total_s')
demo02 = demographie_etrangers.query(" (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="max") 
demo03 = demographie_etrangers.query(" (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM'], columns='NAT2', values='total_s',aggfunc="sum") 

frames = [demo01, demo02, demo03]

result = pd.concat(frames)
result.fillna(0, inplace=True)
result.rename_axis(columns=None, inplace=True)
result.reset_index(inplace=True)

print(result.columns)
print(result.shape) #(1224, 197)
result

Index(['unit', 'NOM', 'Afghans', 'Albanais', 'Algériens', 'Allemands',
       'Américains (U.S.)', 'Andorrans', 'Angolais', 'Antiguais et Barbudiens',
       ...
       'Vanuatuans', 'Vietnamiens', 'Vénézuéliens', 'Yéménites', 'Zambiens',
       'Zaïrois', 'Zimbabwéens', 'etrangers', 'francaisParAcquisition',
       'immigres'],
      dtype='object', length=201)
(1224, 201)

,unit,NOM,Afghans,Albanais,Algériens,Allemands,Américains (U.S.),Andorrans,Angolais,Antiguais et Barbudiens,...,Vanuatuans,Vietnamiens,Vénézuéliens,Yéménites,Zambiens,Zaïrois,Zimbabwéens,etrangers,francaisParAcquisition,immigres
0,200000172,CC Faucigny-Glières,0.0,36.0,344.0,24.0,4.0,0.0,4.0,0.0,...,0.0,87.0,4.0,0.0,0.0,4.0,0.0,2382.0,1789.0,3543.0
1,200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,4.0,4.0,21.0,23.0,4.0,0.0,0.0,0.0,...,0.0,4.0,4.0,0.0,0.0,4.0,0.0,311.0,297.0,528.0
2,200000545,CC des Portes de Romilly-sur-Seine,0.0,0.0,319.0,19.0,4.0,0.0,4.0,0.0,...,0.0,39.0,0.0,0.0,0.0,26.0,0.0,2065.0,1331.0,2787.0
3,200000628,CC Rhône Lez Provence,0.0,0.0,138.0,27.0,4.0,0.0,0.0,0.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,1626.0,1236.0,2338.0
4,200000800,CC Cour de Sologne,0.0,0.0,45.0,4.0,4.0,4.0,0.0,0.0,...,0.0,4.0,0.0,0.0,0.0,4.0,0.0,278.0,264.0,451.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1219,243500741,CA Redon Agglomération,0.0,4.0,48.0,38.0,8.0,0.0,0.0,0.0,...,0.0,8.0,4.0,0.0,0.0,8.0,4.0,1261.0,659.0,1666.0
1220,244400610,CA de la Presqu'île de Guérande Atlantique (Ca...,0.0,0.0,84.0,82.0,38.0,0.0,0.0,0.0,...,0.0,38.0,4.0,0.0,0.0,8.0,0.0,850.0,910.0,1521.0
1221,246100663,CU d'Alençon,108.0,4.0,211.0,43.0,8.0,0.0,19.0,0.0,...,0.0,63.0,4.0,0.0,0.0,110.0,0.0,2801.0,1476.0,3727.0
1222,247600588,CC des Villes Sours,0.0,0.0,21.0,8.0,8.0,0.0,0.0,0.0,...,0.0,8.0,0.0,0.0,0.0,0.0,0.0,247.0,269.0,430.0
1223,248400251,CA du Grand Avignon (COGA),145.0,60.0,4148.0,302.0,116.0,4.0,8.0,0.0,...,0.0,317.0,43.0,0.0,0.0,20.0,4.0,18851.0,12941.0,27168.0

In [ ]:
#result.columns[2:].to_list()
# result.columns[0:2].to_list()

database_wide = result[['unit']]
database_wide['anneeRp'] =  2021
database_wide['indicateur'] =  'NAT_EPCI' #servira de PK avec unit, et anneeRp et permettra de faire le lien avec les autres indicateurs
database_wide['indicateurCode'] =  'NAT2' 
database_wide['indicateurMode'] =  '' 
database_wide['categorie'] = 'Ensemble' #	Etrangers, Français par acquisition,  SecondeGénération, Immigrés	

database_wide = pd.merge(database_wide, result, on=['unit'], how='left') 
print(database_wide.shape)
#(1224, 206) avec les 4 colonnes de unit, anneeRp, indicateur, indicateurCode, indicateurMode, categorie, et les 197 colonnes de nationalités, 'Tous' puis 'etrangers', 'francaisParAcquisition', 'immigres')
database_wide[['unit',  'anneeRp', 'indicateur',  'indicateurCode', 'indicateurMode', 'categorie', 'Tous'] ] 

#database_wide.to_csv('database_wide_demographie_NAT2.csv', index=False)

(1224, 206)

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\3362118785.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide.loc[:, 'anneeRp'] =  2021
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\3362118785.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['indicateur'] =  'NAT_EPCI' #servira de PK avec unit, et anneeRp et permettra de faire le lien avec les autres indicateurs
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\3362118785.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['indicateurCode'] =  'NAT2'
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\3362118785.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['indicateurMode'] =  None
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\3362118785.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['categorie'] = 'Ensemble' #	Etrangers, Français par acquisition,  SecondeGénération, Immigrés

,unit,anneeRp,indicateur,indicateurCode,indicateurMode,categorie,Tous
0,200000172,2021,NAT_EPCI,NAT2,None,Ensemble,27764.0
1,200000438,2021,NAT_EPCI,NAT2,None,Ensemble,36232.0
2,200000545,2021,NAT_EPCI,NAT2,None,Ensemble,18866.0
3,200000628,2021,NAT_EPCI,NAT2,None,Ensemble,24003.0
4,200000800,2021,NAT_EPCI,NAT2,None,Ensemble,10310.0
...,...,...,...,...,...,...,...
1219,243500741,2021,NAT_EPCI,NAT2,None,Ensemble,66837.0
1220,244400610,2021,NAT_EPCI,NAT2,None,Ensemble,76565.0
1221,246100663,2021,NAT_EPCI,NAT2,None,Ensemble,55435.0
1222,247600588,2021,NAT_EPCI,NAT2,None,Ensemble,35817.0
1223,248400251,2021,NAT_EPCI,NAT2,None,Ensemble,194858.0

In [ ]:
engine = create_engine('postgresql://postgres:postgres@localhost:5432/inseedb')
# ORM_conn=engine.connect()
# ORM_conn

#result.to_postgis('NAT', con=ORM_conn , schema='imhana2021', if_exists='replace', index=False)
database_wide.to_sql('RP_EPCI_wide', con=engine.connect(), schema='imhana2021', if_exists='replace', index=False)

# ORM_conn.commit()
# ORM_conn.close()

In [ ]:
result['Tous'].sum() #65 461 180 français en métropole

65461180.0

In [62]:
liste_natio+nationalites_speciales

['Afghans',
 'Albanais',
 'Algériens',
 'Allemands',
 'Américains (U.S.)',
 'Angolais',
 'Arméniens',
 'Australiens',
 'Autrichiens',
 'Belges',
 'Bissao-Guinéens',
 'Biélorusses',
 'Bosniaques',
 'Britanniques',
 'Brésiliens',
 'Bulgares',
 'Burkinabés',
 'Burundais',
 'Béninois',
 'Cambodgiens',
 'Camerounais',
 'Canadiens',
 'Cap-Verdiens',
 'Centrafricains',
 'Chiliens',
 'Chinois',
 'Colombiens',
 'Comoriens',
 'Congolais',
 'Cubains',
 'Danois',
 'Dominicains',
 'Dominiquais',
 'Egyptiens',
 'Equatoriens',
 'Espagnols',
 'Ethiopiens',
 'Fidjiens',
 'Français',
 'Gabonais',
 'Ghanéens',
 'Grecs',
 'Guatémaltèques',
 'Guinéens',
 'Haïtiens',
 'Hongrois',
 'Indiens',
 'Indonésiens',
 'Iraniens',
 'Irlandais',
 'Israéliens',
 'Italiens',
 'Ivoiriens',
 'Japonais',
 'Jordaniens',
 'Libanais',
 'Libyens',
 'Lituaniens',
 'Luxembourgeois',
 'Malaisiens',
 'Malgaches',
 'Maliens',
 'Marocains',
 'Mauriciens',
 'Mauritaniens',
 'Mexicains',
 'Monténégrins',
 'Nigérians',
 'Nigériens',
 'Néerlandais',
 'Népalais',
 'Pakistanais',
 'Palestiniens',
 'Paraguayens',
 'Philippins',
 'Polonais',
 'Portugais',
 'Péruviens',
 'Roumains',
 'Russes',
 'Saint-Luciens',
 'Serbes',
 'Slovaques',
 'Somaliens',
 'Soudanais (2010)',
 'Sri-Lankais',
 'Sud-Africains',
 'Sud-Coréens',
 'Suisses',
 'Surinamais',
 'Suédois',
 'Syriens',
 'Sénégalais',
 'Tchèques',
 'Thaïlandais',
 'Togolais',
 'Tunisiens',
 'Turcs',
 'Ukrainiens',
 'Uruguayens',
 'Vietnamiens',
 'Vénézuéliens',
 'Zaïrois',
 'Croates',
 'Honduriens',
 'Moldaves',
 'Néo-Zélandais',
 'Sierra-Léonais',
 'Tchadiens',
 'Argentins',
 'Bangladais',
 'Djiboutiens',
 'Laotiens',
 'Finlandais',
 'Géorgiens',
 'Iraquiens',
 'Jamaïcains',
 'Lettons',
 'Libériens',
 'Panaméens',
 'Seychellois',
 'Yéménites',
 'Zimbabwéens',
 'Erythréens',
 'Sahariens',
 'Boliviens',
 'Gambiens',
 'Kényans',
 'Mongols',
 'Mozambicains',
 'Rwandais',
 'Slovènes',
 'Maltais',
 'Ouzbeks',
 'Azerbaïdjanais',
 'Chypriotes',
 'Kazakhs',
 'Macédoniens',
 'Norvégiens',
 'Singapouriens',
 'Monégasques',
 'Tonguiens',
 'Turkmènes',
 'Birmans',
 'Costaricains',
 'Barbadiens',
 'Guyaniens',
 'Andorrans',
 'Nicaraguayens',
 'Papouan neo guinéens',
 'Trinidadiens',
 'Koweïtiens',
 'Ougandais',
 'Saint-Marinais',
 'Saoudiens',
 'Taiwanais',
 'Liechtensteinois',
 'Vanuatuans',
 'Maldiviens',
 'Salvadoriens',
 'Estoniens',
 'Islandais',
 'Tanzaniens',
 'Zambiens',
 'Bhoutanais',
 'Santoméens',
 'Tadjiks',
 'Equato-Guinéens',
 'Kirghiz',
 'Antiguais et Barbudiens',
 'Namibiens',
 'Botswanéens',
 'Emiriens',
 'Brunéiens',
 'Saint-Vincentais et Grenadins',
 'Samoans',
 'Grenadiens',
 'Malawiens',
 'Micronésiens',
 'Nord-Coréens',
 'Omanais',
 'Qatariens',
 'Sud-soudanais',
 'Swazis',
 'Salomonais',
 'Bahamiens',
 'Bahreïniens',
 'Béliziens',
 'Lesothans',
 'Nauruans',
 'Palauans',
 'Timoriens',
 'Tuvaluans',
 'Kittitiens et Néviciens',
 'Marshallais',
 'Tous',
 'etrangers',
 'francaisParAcquisition',
 'immigres']

In [72]:
database = result.melt(id_vars=['unit', 'NOM'], value_vars=liste_natio+nationalites_speciales, var_name='NAT2', value_name='total_s')
#Ceci pourrait  être sauvé en base de données
database.dtypes
database = database.astype(dtype = {'unit': 'string', 'NOM': 'string', 'NAT2': 'string', 'total_s': 'int'})
database.rename(columns={'total_s':'POPULATION_NAT2'}, inplace=True)

print(database.dtypes)
database

unit               string
NOM                string
NAT2               string
POPULATION_NAT2     int32
dtype: object

,unit,NOM,NAT2,POPULATION_NAT2
0,200000172,CC Faucigny-Glières,Afghans,0
1,200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,Afghans,4
2,200000545,CC des Portes de Romilly-sur-Seine,Afghans,0
3,200000628,CC Rhône Lez Provence,Afghans,0
4,200000800,CC Cour de Sologne,Afghans,0
...,...,...,...,...
243571,243500741,CA Redon Agglomération,immigres,1666
243572,244400610,CA de la Presqu'île de Guérande Atlantique (Ca...,immigres,1521
243573,246100663,CU d'Alençon,immigres,3727
243574,247600588,CC des Villes Sours,immigres,430
243575,248400251,CA du Grand Avignon (COGA),immigres,27168

In [75]:
print(database.shape) #(243576, 4)
print(database.columns) #['unit', 'NOM', 'NAT2', 'POPULATION_NAT2']

(243576, 4)
Index(['unit', 'NOM', 'NAT2', 'POPULATION_NAT2'], dtype='object')

In [308]:
database.to_csv('database_demographie_NAT2.csv', index=False)

In [ ]:
import pandas.io.sql as sql
from sqlalchemy import create_engine

""" engine = create_engine('postgresql://postgres:postgres@localhost:5432/inseedb')
ORM_conn=engine.connect()
#ORM_conn

#result.to_postgis('NAT', con=ORM_conn , schema='imhana2021', if_exists='replace', index=False)
result.to_sql('NAT', con=ORM_conn , schema='imhana2021', if_exists='replace', index=False)

ORM_conn.commit()
ORM_conn.close() """

def save_to_database(df, table_name, schema_name='imhana2021'):
    from sqlalchemy import create_engine
    engine = create_engine('postgresql://postgres:postgres@localhost:5432/inseedb')
    with engine.connect() as connection:
        df.to_sql(table_name, con=connection, schema=schema_name, if_exists='replace', index=False)
        connection.commit()
        connection.close()

## Vérification sur les fichiers originaux (même problème de doublons ?)

oui, idem

In [338]:
nat_epci_file = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD\2026-01-27\2026.01.22\EPCI\_NAT_EPCI_2026.01.22.csv"

demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')

In [339]:
demographie_etrangers[demographie_etrangers.unit == '200057867'] #EPT Plaine Commune n'est pas dans les données de démographie

Empty DataFrame
Columns: [unit, NAT_rec2, total_s]
Index: []

In [ ]:

demographie_etrangers[demographie_etrangers.unit == '248500191'] #l'île de Noirmoutiers est dans les données de démographie

In [ ]:
testdoublons = demographie_etrangers.query("NAT_rec2 == 'Tous'").groupby('unit').count().sort_values(by='total_s').query("total_s != 1").sort_values(by='unit') 
#testdoublons = demographie_etrangers.query("NAT2 == 'Tous'").groupby('unit').count().sort_values(by='total_s').query("total_s != 1").sort_values(by='unit') 

#.NAT_rec2.unique().apply(lambda x: 'Tous' in x and 'etrangers' in x and 'francaisParAcquisition' in x and 'immigres' in x)
print(testdoublons.shape) #(26, 2)
testdoublons

## Réponse, oui, même problème que précédemment, les EPCI à cheval sur deux régions apparaissent en double compte dans mon export

## Lire les données avec INAT

In [69]:
nat_epci_file = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\2026.01.22\EPCI\INAT_NAT_EPCI_2026.01.22.csv"
demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)

EPT_Paris = ['200057867','200057875','200057941','200057966','200057974','200057982','200057990','200058006','200058014','200058097','200058790']
EPCI_fictives = ['HORS__GFP', 'RESTANT__GFP', 'fictive_200027399', 'fictive_242320034', 'fictive_242320059', 'fictive_244701389']

nationalites_speciales = ['Tous', 'etrangers', 'francaisParAcquisition', 'immigres']
liste_natio = pd.read_csv('liste_nationalites.csv')['nationalites'].tolist()

doublons_CC_EPCI = pd.read_csv('doublons_CC_EPCI.csv', sep=';', encoding='utf-8', dtype={'doublons_CC_EPCI':str})['doublons_CC_EPCI'].tolist()
doublons_CA_CU_EPCI = pd.read_csv('doublons_CA_CU_EPCI.csv', sep=';', encoding='utf-8', dtype={'doublons_CA_CU_EPCI':str})['doublons_CA_CU_EPCI'].tolist()

print(doublons_CC_EPCI)
print(doublons_CA_CU_EPCI)

STRANGERS = ['Etranger', 'Français par acquisition']
FRENCH_DOMTOM = pd.read_csv('FRENCH_DOMTOM.csv', sep=';', encoding='utf-8', dtype={'FRENCH_DOMTOM':str})['FRENCH_DOMTOM'].tolist()
#FRENCH_DOMTOM = demographie_etrangers.query("INAT_BIS.str.startswith('Français') and INAT_BIS != 'Français par acquisition'").INAT_BIS.unique()
print(FRENCH_DOMTOM)
epci = gpd.read_file('epci_with_demo_metropole2154_.gpkg')

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\2108954388.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')

['200072106', '200066462', '200071033', '200071884', '200068088', '200072676', '246401756', '248400335', '200035723', '200030435', '200035129', '200067668', '248200016', '200070332', '247800550', '200068765', '200069722', '200071140', '200070308']
['200040277', '243500741', '244400610', '248400251', '246100663', '200040681', '247600588']
['Français Guadeloupe (971)', 'Français Guyane (973)', 'Français La Réunion (974)', 'Français Martinique (972)', 'Français Mayotte (976)', 'Français Metropole', 'Français Nouvelle-Calédonie (988)', 'Français Polynésie Française (987)', 'Français Saint-Martin (978)', 'Français Saint-Pierre-et-Miquelon (975)', 'Français Wallis et Futuna (986)', 'Français Saint-Barthélemy (977)']

In [70]:
FRENCH_DOMTOM_df = pd.DataFrame({'FRENCH_DOMTOM': FRENCH_DOMTOM})
FRENCH_DOMTOM_df.to_csv('FRENCH_DOMTOM.csv', index=False)
print(FRENCH_DOMTOM)

['Français Guadeloupe (971)', 'Français Guyane (973)', 'Français La Réunion (974)', 'Français Martinique (972)', 'Français Mayotte (976)', 'Français Metropole', 'Français Nouvelle-Calédonie (988)', 'Français Polynésie Française (987)', 'Français Saint-Martin (978)', 'Français Saint-Pierre-et-Miquelon (975)', 'Français Wallis et Futuna (986)', 'Français Saint-Barthélemy (977)']

In [71]:
print(demographie_etrangers.columns)
demographie_etrangers.query("unit == '200023307'") #CC de l'Île de Noirmoutier
print(pd.unique(demographie_etrangers.INAT_BIS))

STRANGERS = ['Etranger', 'Français par acquisition']
print(STRANGERS)

#demographie_etrangers.query("unit == 248500191") ## CA du Grand Villeneuvois
FRENCH_DOMTOM = demographie_etrangers.query("INAT_BIS.str.startswith('Français') and INAT_BIS != 'Français par acquisition'").INAT_BIS.unique()

print(FRENCH_DOMTOM)

demographie_etrangers.query("unit == '248500191' ")

Index(['unit', 'INAT_BIS', 'NAT2', 'total_s', 'NOM'], dtype='object')
['Etranger' 'Français Guadeloupe (971)' 'Français Guyane (973)'
 'Français La Réunion (974)' 'Français Martinique (972)'
 'Français Mayotte (976)' 'Français Metropole'
 'Français Nouvelle-Calédonie (988)' 'Français Polynésie Française (987)'
 'Français Saint-Martin (978)' 'Français Saint-Pierre-et-Miquelon (975)'
 'Français par acquisition' 'Français Wallis et Futuna (986)'
 'Français Saint-Barthélemy (977)' '*']
['Etranger', 'Français par acquisition']
['Français Guadeloupe (971)' 'Français Guyane (973)'
 'Français La Réunion (974)' 'Français Martinique (972)'
 'Français Mayotte (976)' 'Français Metropole'
 'Français Nouvelle-Calédonie (988)' 'Français Polynésie Française (987)'
 'Français Saint-Martin (978)' 'Français Saint-Pierre-et-Miquelon (975)'
 'Français Wallis et Futuna (986)' 'Français Saint-Barthélemy (977)']

,unit,INAT_BIS,NAT2,total_s,NOM
87214,248500191,Etranger,Algériens,4,CC de l'Île de Noirmoutier
87215,248500191,Etranger,Allemands,4,CC de l'Île de Noirmoutier
87216,248500191,Etranger,Américains (U.S.),4,CC de l'Île de Noirmoutier
87217,248500191,Etranger,Argentins,4,CC de l'Île de Noirmoutier
87218,248500191,Etranger,Belges,19,CC de l'Île de Noirmoutier
...,...,...,...,...,...
87278,248500191,Français par acquisition,Vietnamiens,4,CC de l'Île de Noirmoutier
88350,248500191,*,Tous,9219,CC de l'Île de Noirmoutier
88421,248500191,*,immigres,137,CC de l'Île de Noirmoutier
88492,248500191,*,francaisParAcquisition,75,CC de l'Île de Noirmoutier
88563,248500191,*,etrangers,77,CC de l'Île de Noirmoutier

In [72]:
resumesTous = demographie_etrangers.query("unit == 248500191 and (NAT2 in @nationalites_speciales ) and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', 'INAT_BIS'], columns='NAT2', values='total_s')
# or INAT_BIS in @FRENCH_DOMTOM
resumesTous.fillna(0, inplace=True)
resumesTous.rename_axis(columns=None, inplace=True)
resumesTous.reset_index(inplace=True)
resumesTous

Empty DataFrame
Columns: [unit, NOM, INAT_BIS]
Index: []

In [73]:
#test = demographie_etrangers.copy()
demographie_etrangers.query("unit == 248500191").loc[demographie_etrangers['INAT_BIS'] == 'Français Martinique (972)', 'total_s'] #4
demographie_etrangers.query("unit == 248500191").loc[demographie_etrangers['INAT_BIS'].isin(FRENCH_DOMTOM), 'total_s'] #4

#test.query("unit == 248500191").loc[demographie_etrangers['INAT_BIS'].isin(FRENCH_DOMTOM), 'NAT2'] = test.query("unit == 248500191").loc[demographie_etrangers['INAT_BIS'].isin(FRENCH_DOMTOM), 'INAT_BIS'] 

demographie_etrangers.query("unit == 248500191").loc[demographie_etrangers['INAT_BIS'].isin(FRENCH_DOMTOM), 'total_s'] #4
# 87241       4
# 87242       4
# 87243       4
# 87244       4
# 87245    9040
# 87246       4
test = demographie_etrangers.query("unit == 248500191 and INAT_BIS in @FRENCH_DOMTOM").pivot(index=['unit', 'NOM'], columns='INAT_BIS', values='total_s')
test.fillna(0, inplace=True)
test.rename_axis(columns=None, inplace=True)
test.reset_index(inplace=True)
test

Empty DataFrame
Columns: [unit, NOM]
Index: []

In [74]:
test02 = pd.merge(resumesTous , test, how='inner', on=['unit', 'NOM'])
test02.fillna(0, inplace=True)
test02.rename_axis(columns=None, inplace=True)
#test01.reset_index(inplace=True)
test02

Empty DataFrame
Columns: [INAT_BIS, unit, NOM]
Index: []

#### En résumé, pour faire test01

In [75]:

resumesTous = demographie_etrangers.query("unit == '248500191' and (NAT2 in @nationalites_speciales ) and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', 'INAT_BIS'], columns='NAT2', values='total_s')
# or INAT_BIS in @FRENCH_DOMTOM
resumesTous.fillna(0, inplace=True)
resumesTous.rename_axis(columns=None, inplace=True)
resumesTous.reset_index(inplace=True)
resumesTous

## Récupérer les données de démographie pour les Français des DOM-TOM
francais = demographie_etrangers.query("unit == '248500191' and INAT_BIS in @FRENCH_DOMTOM").pivot(index=['unit', 'NOM'], columns='INAT_BIS', values='total_s')
francais.fillna(0, inplace=True)
francais.rename_axis(columns=None, inplace=True)
francais.reset_index(inplace=True)
francais

## aligner avec les données de démographie pour les étrangers (Tous, etrangers, francaisParAcquisition, immigres)
test01 = pd.merge(resumesTous , francais, how='inner', on=['unit', 'NOM'])
test01.fillna(0, inplace=True)
test01.rename_axis(columns=None, inplace=True)
#test01.reset_index(inplace=True)
test01

,unit,NOM,INAT_BIS,Tous,etrangers,francaisParAcquisition,immigres,Français Guadeloupe (971),Français Guyane (973),Français La Réunion (974),Français Martinique (972),Français Metropole,Français Polynésie Française (987)
0,248500191,CC de l'Île de Noirmoutier,*,9219,77,75,137,4,4,4,4,9040,4

In [76]:
demo01a = demographie_etrangers.query("unit == '248500191' and INAT_BIS in @STRANGERS and NAT2 not in @nationalites_speciales and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', 'INAT_BIS'], columns='NAT2', values='total_s')
#
demo01a.fillna(0, inplace=True)
demo01a.rename_axis(columns=None, inplace=True)
demo01a.reset_index(inplace=True)
demo01a

,unit,NOM,INAT_BIS,Algériens,Allemands,Américains (U.S.),Angolais,Argentins,Arméniens,Belges,...,Suisses,Surinamais,Suédois,Sénégalais,Tanzaniens,Thaïlandais,Tunisiens,Ukrainiens,Vietnamiens,Zaïrois
0,248500191,CC de l'Île de Noirmoutier,Etranger,4.0,4.0,4.0,0.0,4.0,0.0,19.0,...,0.0,0.0,4.0,4.0,4.0,4.0,4.0,0.0,0.0,4.0
1,248500191,CC de l'Île de Noirmoutier,Français par acquisition,4.0,4.0,4.0,4.0,0.0,4.0,4.0,...,4.0,4.0,4.0,4.0,0.0,0.0,4.0,4.0,4.0,0.0

In [77]:
frames = [demo01a, test02]

result = pd.concat(frames)
result.fillna(0, inplace=True)
#result.rename_axis(columns=None, inplace=True)
#result.reset_index(inplace=True)
result

#Bof : gros gaspillage de place pour INAT_BIS= *

,unit,NOM,INAT_BIS,Algériens,Allemands,Américains (U.S.),Angolais,Argentins,Arméniens,Belges,...,Suisses,Surinamais,Suédois,Sénégalais,Tanzaniens,Thaïlandais,Tunisiens,Ukrainiens,Vietnamiens,Zaïrois
0,248500191,CC de l'Île de Noirmoutier,Etranger,4.0,4.0,4.0,0.0,4.0,0.0,19.0,...,0.0,0.0,4.0,4.0,4.0,4.0,4.0,0.0,0.0,4.0
1,248500191,CC de l'Île de Noirmoutier,Français par acquisition,4.0,4.0,4.0,4.0,0.0,4.0,4.0,...,4.0,4.0,4.0,4.0,0.0,0.0,4.0,4.0,4.0,0.0

In [78]:
pd.merge(demo01a , test01.drop(columns=['INAT_BIS']), how='inner', on=['unit', 'NOM'])
# Bonne solution

,unit,NOM,INAT_BIS,Algériens,Allemands,Américains (U.S.),Angolais,Argentins,Arméniens,Belges,...,Tous,etrangers,francaisParAcquisition,immigres,Français Guadeloupe (971),Français Guyane (973),Français La Réunion (974),Français Martinique (972),Français Metropole,Français Polynésie Française (987)
0,248500191,CC de l'Île de Noirmoutier,Etranger,4.0,4.0,4.0,0.0,4.0,0.0,19.0,...,9219,77,75,137,4,4,4,4,9040,4
1,248500191,CC de l'Île de Noirmoutier,Français par acquisition,4.0,4.0,4.0,4.0,0.0,4.0,4.0,...,9219,77,75,137,4,4,4,4,9040,4

#### Passage à l'échelle : sur toutes les unités EPCI

Il faut convertir en string unit ? OUI

In [79]:
demographie_etrangers.query("unit == 'HORS__GFP'")
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)
demographie_etrangers.query("unit == '247600588'") #CC des Villes Sours

,unit,INAT_BIS,NAT2,total_s,NOM
41933,247600588,Etranger,Algériens,4,CC des Villes Sours
41934,247600588,Etranger,Allemands,4,CC des Villes Sours
41935,247600588,Etranger,Américains (U.S.),4,CC des Villes Sours
41936,247600588,Etranger,Argentins,4,CC des Villes Sours
41937,247600588,Etranger,Belges,24,CC des Villes Sours
...,...,...,...,...,...
78379,247600588,Français par acquisition,Vietnamiens,4,CC des Villes Sours
78847,247600588,*,Tous,21966,CC des Villes Sours
78916,247600588,*,immigres,283,CC des Villes Sours
78985,247600588,*,francaisParAcquisition,189,CC des Villes Sours
79054,247600588,*,etrangers,152,CC des Villes Sours

In [80]:
testdoublons = demographie_etrangers.query("NAT2 == 'Tous'").groupby('unit').count().sort_values(by='total_s').query("total_s != 1").sort_values(by='unit') 
#testdoublons = demographie_etrangers.query("NAT2 == 'Tous'").groupby('unit').count().sort_values(by='total_s').query("total_s != 1").sort_values(by='unit') 

#.NAT_rec2.unique().apply(lambda x: 'Tous' in x and 'etrangers' in x and 'francaisParAcquisition' in x and 'immigres' in x)
print(testdoublons.shape) #(26, 2)
testdoublons

(26, 4)

           INAT_BIS  NAT2  total_s  NOM
unit
200030435         2     2        2    2
200035129         2     2        2    2
200035723         2     2        2    2
200040277         2     2        2    2
200040681         2     2        2    2
200066462         2     2        2    2
200067668         2     2        2    2
200068088         2     2        2    2
200068765         2     2        2    2
200069722         2     2        2    2
200070308         2     2        2    2
200070332         2     2        2    2
200071033         2     2        2    2
200071140         2     2        2    2
200071884         2     2        2    2
200072106         2     2        2    2
200072676         2     2        2    2
243500741         2     2        2    2
244400610         2     2        2    2
246100663         2     2        2    2
246401756         2     2        2    2
247600588         2     2        2    2
247800550         2     2        2    2
248200016         2     2        2    2
248400251         2     2        2    2
248400335         2     2        2    2

In [81]:
demo01a = demographie_etrangers.query("INAT_BIS in @STRANGERS and NAT2 not in @nationalites_speciales and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', 'INAT_BIS'], columns='NAT2', values='total_s')
#
demo01a.fillna(0, inplace=True)
demo01a.rename_axis(columns=None, inplace=True)
demo01a.reset_index(inplace=True)
demo01a

,unit,NOM,INAT_BIS,Afghans,Albanais,Algériens,Allemands,Américains (U.S.),Andorrans,Angolais,...,Tuvaluans,Ukrainiens,Uruguayens,Vanuatuans,Vietnamiens,Vénézuéliens,Yéménites,Zambiens,Zaïrois,Zimbabwéens
0,200000172,CC Faucigny-Glières,Etranger,0.0,35.0,144.0,21.0,4.0,0.0,4.0,...,0.0,17.0,0.0,0.0,32.0,4.0,0.0,0.0,4.0,0.0
1,200000172,CC Faucigny-Glières,Français par acquisition,0.0,4.0,200.0,4.0,4.0,0.0,0.0,...,0.0,0.0,4.0,0.0,55.0,0.0,0.0,0.0,4.0,0.0
2,200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,Etranger,0.0,4.0,4.0,16.0,0.0,0.0,0.0,...,0.0,4.0,0.0,0.0,4.0,4.0,0.0,0.0,4.0,0.0
3,200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,Français par acquisition,4.0,0.0,4.0,4.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0
4,200000545,CC des Portes de Romilly-sur-Seine,Etranger,0.0,0.0,223.0,4.0,4.0,0.0,4.0,...,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,17.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2391,249500455,CC de la Vallée de l'Oise et des Trois Forêts,Français par acquisition,0.0,4.0,233.0,4.0,4.0,0.0,4.0,...,0.0,4.0,0.0,0.0,42.0,4.0,0.0,0.0,35.0,0.0
2392,249500489,CC du Haut Val d'Oise,Etranger,66.0,0.0,787.0,26.0,4.0,0.0,35.0,...,0.0,4.0,0.0,0.0,4.0,4.0,0.0,0.0,186.0,0.0
2393,249500489,CC du Haut Val d'Oise,Français par acquisition,4.0,4.0,594.0,4.0,0.0,0.0,4.0,...,0.0,4.0,0.0,0.0,28.0,0.0,0.0,0.0,132.0,0.0
2394,249500513,CC du Vexin-Val de Seine,Etranger,0.0,0.0,38.0,4.0,4.0,0.0,4.0,...,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0
2395,249500513,CC du Vexin-Val de Seine,Français par acquisition,0.0,0.0,58.0,4.0,4.0,0.0,4.0,...,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0

In [82]:
resumesTous = demographie_etrangers.query("(NAT2 in @nationalites_speciales ) and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', 'INAT_BIS'], columns='NAT2', values='total_s')
# or INAT_BIS in @FRENCH_DOMTOM
resumesTous.fillna(0, inplace=True)
resumesTous.rename_axis(columns=None, inplace=True)
resumesTous.reset_index(inplace=True)
resumesTous

# ## Récupérer les données de démographie pour les Français des DOM-TOM / unit == 248500191 and 
francais = demographie_etrangers.query("INAT_BIS in @FRENCH_DOMTOM and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM'], columns='INAT_BIS', values='total_s')
francais.fillna(0, inplace=True)
francais.rename_axis(columns=None, inplace=True)
francais.reset_index(inplace=True)
francais

# ## aligner avec les données de démographie pour les étrangers (Tous, etrangers, francaisParAcquisition, immigres)
test01 = pd.merge(resumesTous , francais, how='inner', on=['unit', 'NOM'])
test01.fillna(0, inplace=True)
test01.rename_axis(columns=None, inplace=True)
#test01.reset_index(inplace=True)
test01

,unit,NOM,INAT_BIS,Tous,etrangers,francaisParAcquisition,immigres,Français Guadeloupe (971),Français Guyane (973),Français La Réunion (974),Français Martinique (972),Français Mayotte (976),Français Metropole,Français Nouvelle-Calédonie (988),Français Polynésie Française (987),Français Saint-Barthélemy (977),Français Saint-Martin (978),Français Saint-Pierre-et-Miquelon (975),Français Wallis et Futuna (986)
0,200000172,CC Faucigny-Glières,*,27764,2382,1789,3543,4.0,17.0,89.0,16.0,26.0,23425.0,4.0,4.0,0.0,0.0,0.0,0.0
1,200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,*,36232,311,297,528,26.0,4.0,34.0,4.0,21.0,35511.0,4.0,4.0,4.0,4.0,4.0,0.0
2,200000545,CC des Portes de Romilly-sur-Seine,*,18866,2065,1331,2787,151.0,42.0,85.0,135.0,4.0,15038.0,4.0,4.0,0.0,4.0,0.0,0.0
3,200000628,CC Rhône Lez Provence,*,24003,1626,1236,2338,16.0,4.0,31.0,4.0,4.0,21077.0,0.0,4.0,0.0,0.0,0.0,0.0
4,200000800,CC Cour de Sologne,*,10310,278,264,451,4.0,4.0,31.0,4.0,4.0,9712.0,4.0,4.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1193,249500109,CA de Cergy-Pontoise,*,214428,32802,21028,44060,1856.0,333.0,551.0,1511.0,78.0,156182.0,37.0,32.0,0.0,17.0,4.0,0.0
1194,249500430,CC Sausseron Impressionnistes,*,19061,825,759,1258,30.0,4.0,41.0,38.0,0.0,17348.0,4.0,4.0,0.0,0.0,4.0,0.0
1195,249500455,CC de la Vallée de l'Oise et des Trois Forêts,*,39019,2959,2057,3998,121.0,29.0,80.0,110.0,4.0,33640.0,4.0,4.0,0.0,4.0,4.0,0.0
1196,249500489,CC du Haut Val d'Oise,*,39726,5084,3133,6601,474.0,80.0,92.0,355.0,4.0,30499.0,4.0,4.0,0.0,0.0,0.0,0.0
1197,249500513,CC du Vexin-Val de Seine,*,16622,699,599,1074,64.0,4.0,58.0,56.0,4.0,15132.0,4.0,4.0,0.0,0.0,0.0,0.0

In [83]:
result = pd.merge(demo01a , test01.drop(columns=['INAT_BIS']), how='inner', on=['unit', 'NOM'])
result

result.rename(columns={'INAT_BIS': 'Categorie'}, inplace=True)
result

result.rename(columns={'NOM': 'Indicateur'}, inplace=True)
result.Indicateur = 'INAT_NAT' + '_' + result.Categorie
result

,unit,Indicateur,Categorie,Afghans,Albanais,Algériens,Allemands,Américains (U.S.),Andorrans,Angolais,...,Français La Réunion (974),Français Martinique (972),Français Mayotte (976),Français Metropole,Français Nouvelle-Calédonie (988),Français Polynésie Française (987),Français Saint-Barthélemy (977),Français Saint-Martin (978),Français Saint-Pierre-et-Miquelon (975),Français Wallis et Futuna (986)
0,200000172,INAT_NAT_Etranger,Etranger,0.0,35.0,144.0,21.0,4.0,0.0,4.0,...,89.0,16.0,26.0,23425.0,4.0,4.0,0.0,0.0,0.0,0.0
1,200000172,INAT_NAT_Français par acquisition,Français par acquisition,0.0,4.0,200.0,4.0,4.0,0.0,0.0,...,89.0,16.0,26.0,23425.0,4.0,4.0,0.0,0.0,0.0,0.0
2,200000438,INAT_NAT_Etranger,Etranger,0.0,4.0,4.0,16.0,0.0,0.0,0.0,...,34.0,4.0,21.0,35511.0,4.0,4.0,4.0,4.0,4.0,0.0
3,200000438,INAT_NAT_Français par acquisition,Français par acquisition,4.0,0.0,4.0,4.0,4.0,0.0,0.0,...,34.0,4.0,21.0,35511.0,4.0,4.0,4.0,4.0,4.0,0.0
4,200000545,INAT_NAT_Etranger,Etranger,0.0,0.0,223.0,4.0,4.0,0.0,4.0,...,85.0,135.0,4.0,15038.0,4.0,4.0,0.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2391,249500455,INAT_NAT_Français par acquisition,Français par acquisition,0.0,4.0,233.0,4.0,4.0,0.0,4.0,...,80.0,110.0,4.0,33640.0,4.0,4.0,0.0,4.0,4.0,0.0
2392,249500489,INAT_NAT_Etranger,Etranger,66.0,0.0,787.0,26.0,4.0,0.0,35.0,...,92.0,355.0,4.0,30499.0,4.0,4.0,0.0,0.0,0.0,0.0
2393,249500489,INAT_NAT_Français par acquisition,Français par acquisition,4.0,4.0,594.0,4.0,0.0,0.0,4.0,...,92.0,355.0,4.0,30499.0,4.0,4.0,0.0,0.0,0.0,0.0
2394,249500513,INAT_NAT_Etranger,Etranger,0.0,0.0,38.0,4.0,4.0,0.0,4.0,...,58.0,56.0,4.0,15132.0,4.0,4.0,0.0,0.0,0.0,0.0
2395,249500513,INAT_NAT_Français par acquisition,Français par acquisition,0.0,0.0,58.0,4.0,4.0,0.0,4.0,...,58.0,56.0,4.0,15132.0,4.0,4.0,0.0,0.0,0.0,0.0

##### doublons EPCI - CC

Prendre le max

In [84]:
demo02a = demographie_etrangers.query("INAT_BIS in @STRANGERS and NAT2 not in @nationalites_speciales and not(unit in @EPCI_fictives) and unit in @doublons_CC_EPCI ").pivot_table(index=['unit', 'NOM', 'INAT_BIS'], columns='NAT2', values='total_s', aggfunc="max")
#NAT2 in @nationalites_speciales and (unit in @doublons_CC_EPCI)
demo02a.fillna(0, inplace=True)
demo02a.rename_axis(columns=None, inplace=True)
demo02a.reset_index(inplace=True)
demo02a

# resumesTous = demographie_etrangers.query("(NAT2 in @nationalites_speciales ) and not(unit in @EPCI_fictives) and unit in @doublons_CC_EPCI").pivot_table(index=['unit', 'NOM', 'INAT_BIS'], columns='NAT2', values='total_s', aggfunc="max")
# # or INAT_BIS in @FRENCH_DOMTOM
# resumesTous.fillna(0, inplace=True)
# resumesTous.rename_axis(columns=None, inplace=True)
# resumesTous.reset_index(inplace=True)
# resumesTous

# # ## Récupérer les données de démographie pour les Français des DOM-TOM / unit == 248500191 and 
# francais = demographie_etrangers.query("INAT_BIS in @FRENCH_DOMTOM and not(unit in @EPCI_fictives) and unit in @doublons_CC_EPCI").pivot_table(index=['unit', 'NOM'], columns='INAT_BIS', values='total_s', aggfunc="max")
# francais.fillna(0, inplace=True)
# francais.rename_axis(columns=None, inplace=True)
# francais.reset_index(inplace=True)
# francais

# # ## aligner avec les données de démographie pour les étrangers (Tous, etrangers, francaisParAcquisition, immigres)
# demo02b = pd.merge(resumesTous , francais, how='inner', on=['unit', 'NOM'])
# demo02b.fillna(0, inplace=True)
# demo02b.rename_axis(columns=None, inplace=True)
# demo02b.drop(columns=['INAT_BIS'], inplace=True)
# #test01.reset_index(inplace=True)
# print(demo02b.columns)
# demo02b

# ## Fusionner les étrangers (toutes les lignes) avec la ligne Tous, etrangers, francaisParAcquisition, immigres + Français*
# result = pd.merge(demo02a , demo02b), how='inner', on=['unit', 'NOM'])

# # A terme, Categorie vaudra : Ensemble (fichier NAT), [Etranger, Français par acquisition] (fichier INAT_NAT), secondeGénération (fichier GEN2_NAT), immigrés (fichier IMMI_NAT)
# result.rename(columns={'INAT_BIS': 'Categorie'}, inplace=True)
# #je remplace le nom des unités par un nom d'indicateur
# result.rename(columns={'NOM': 'Indicateur'}, inplace=True) 
# result.Indicateur = 'INAT_NAT' + '_' + result.Categorie 
# result

,unit,NOM,INAT_BIS,Afghans,Albanais,Algériens,Allemands,Américains (U.S.),Angolais,Argentins,...,Turcs,Turkmènes,Ukrainiens,Uruguayens,Vanuatuans,Vietnamiens,Vénézuéliens,Yéménites,Zaïrois,Zimbabwéens
0,200030435,CC d'Aire-sur-l'Adour,Etranger,41.0,0.0,4.0,4.0,0.0,0.0,4.0,...,4.0,0.0,4.0,4.0,0.0,0.0,4.0,0.0,4.0,0.0
1,200030435,CC d'Aire-sur-l'Adour,Français par acquisition,0.0,0.0,4.0,4.0,4.0,0.0,0.0,...,0.0,0.0,4.0,0.0,0.0,4.0,4.0,0.0,4.0,0.0
2,200035129,CC de Cèze Cévennes,Etranger,4.0,0.0,63.0,32.0,4.0,0.0,4.0,...,18.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0
3,200035129,CC de Cèze Cévennes,Français par acquisition,0.0,0.0,46.0,18.0,4.0,0.0,4.0,...,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
4,200035723,CC Ventoux Sud,Etranger,0.0,4.0,4.0,45.0,4.0,0.0,4.0,...,4.0,4.0,80.0,0.0,4.0,4.0,4.0,0.0,0.0,0.0
5,200035723,CC Ventoux Sud,Français par acquisition,0.0,0.0,4.0,4.0,0.0,0.0,0.0,...,4.0,0.0,4.0,0.0,0.0,4.0,4.0,0.0,0.0,4.0
6,200066462,CC Interco Normandie Sud Eure,Etranger,4.0,4.0,69.0,4.0,4.0,4.0,4.0,...,95.0,0.0,4.0,4.0,0.0,4.0,4.0,0.0,4.0,0.0
7,200066462,CC Interco Normandie Sud Eure,Français par acquisition,0.0,4.0,40.0,4.0,4.0,0.0,0.0,...,44.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0
8,200067668,"CC de la Cléry, du Betz et de l'Ouanne",Etranger,0.0,0.0,28.0,4.0,4.0,0.0,4.0,...,16.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
9,200067668,"CC de la Cléry, du Betz et de l'Ouanne",Français par acquisition,0.0,4.0,28.0,4.0,0.0,4.0,4.0,...,4.0,0.0,4.0,0.0,0.0,4.0,4.0,0.0,4.0,0.0
10,200068088,CC Les Bertranges,Etranger,4.0,4.0,4.0,4.0,0.0,0.0,0.0,...,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0
11,200068088,CC Les Bertranges,Français par acquisition,4.0,4.0,4.0,4.0,4.0,0.0,0.0,...,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0
12,200068765,CC du Sisteronais-Buëch,Etranger,19.0,0.0,68.0,67.0,4.0,0.0,4.0,...,4.0,0.0,4.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0
13,200068765,CC du Sisteronais-Buëch,Français par acquisition,4.0,0.0,119.0,28.0,4.0,0.0,0.0,...,4.0,0.0,4.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0
14,200069722,CC interrégionale Aumale - Blangy-sur-Bresle,Etranger,4.0,0.0,24.0,4.0,4.0,0.0,0.0,...,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
15,200069722,CC interrégionale Aumale - Blangy-sur-Bresle,Français par acquisition,0.0,0.0,4.0,4.0,0.0,0.0,0.0,...,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0
16,200070308,CA Mâconnais Beaujolais Agglomération,Etranger,30.0,43.0,563.0,60.0,4.0,39.0,4.0,...,1181.0,0.0,25.0,0.0,0.0,4.0,0.0,0.0,56.0,0.0
17,200070308,CA Mâconnais Beaujolais Agglomération,Français par acquisition,0.0,4.0,494.0,34.0,4.0,24.0,0.0,...,504.0,0.0,4.0,0.0,0.0,21.0,0.0,0.0,26.0,0.0
18,200070332,CC des Savoir-Faire,Etranger,0.0,4.0,4.0,23.0,4.0,0.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
19,200070332,CC des Savoir-Faire,Français par acquisition,0.0,0.0,4.0,4.0,0.0,0.0,0.0,...,4.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,200071033,CC Jabron-Lure-Vançon-Durance,Etranger,0.0,0.0,4.0,4.0,4.0,0.0,4.0,...,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
21,200071033,CC Jabron-Lure-Vançon-Durance,Français par acquisition,0.0,0.0,20.0,4.0,0.0,0.0,4.0,...,4.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
22,200071140,CA Moulins Communauté,Etranger,95.0,28.0,156.0,19.0,4.0,4.0,0.0,...,112.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,21.0,0.0
23,200071140,CA Moulins Communauté,Français par acquisition,4.0,4.0,121.0,4.0,4.0,0.0,4.0,...,44.0,0.0,0.0,4.0,0.0,20.0,0.0,0.0,4.0,0.0
24,200071884,CC Le Grand Charolais,Etranger,46.0,38.0,56.0,4.0,4.0,4.0,4.0,...,39.0,0.0,4.0,0.0,0.0,4.0,0.0,4.0,4.0,0.0
25,200071884,CC Le Grand Charolais,Français par acquisition,4.0,4.0,64.0,4.0,4.0,4.0,0.0,...,27.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
26,200072106,CC Adour Madiran,Etranger,4.0,4.0,4.0,4.0,4.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
27,200072106,CC Adour Madiran,Français par acquisition,4.0,0.0,22.0,4.0,4.0,4.0,4.0,...,0.0,0.0,4.0,4.0,0.0,4.0,0.0,0.0,4.0,0.0
28,200072676,CC Maine Saosnois,Etranger,0.0,0.0,18.0,18.0,4.0,0.0,0.0,...,4.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
29,200072676,CC Maine Saosnois,Français par acquisition,0.0,0.0,4.0,4.0,4.0,0.0,4.0,...,4.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
30,246401756,CC Pays de Nay,Etranger,0.0,0.0,4.0,4.0,4.0,0.0,0.0,...,4.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
31,246401756,CC Pays de Nay,Français par acquisition,0.0,0.0,4.0,4.0,4.0,0.0,4.0,...,4.0,0.0,4.0,4.0,0.0,4.0,0.0,0.0,4.0,0.0
32,247800550,CC du Pays Houdanais (CCPH),Etranger,18.0,0.0,52.0,21.0,4.0,0.0,4.0,...,4.0,0.0,4.0,0.0,0.0,4.0,4.0,0.0,4.0,0.0
33,247800550,CC du Pays Houdanais (CCPH),Français par acquisition,4.0,4.0,49.0,4.0,4.0,0.0,0.0,...,4.0,0.0,4.0,4.0,0.0,21.0,4.0,0.0,4.0,0.0
34,248200016,CC des Deux Rives,Etranger,0.0,0.0,34.0,4.0,4.0,0.0,4.0,...,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
35,248200016,CC des Deux Rives,Français par acquisition,0.0,0.0,46.0,4.0,4.0,0.0,0.0,...,0.0,0.0,4.0,4.0,0.0,4.0,0.0,0.0,4.0,0.0
36,248400335,CC Vaison Ventoux,Etranger,0.0,0.0,22.0,57.0,18.0,0.0,0.0,...,22.0,0.0,4.0,0.0,0.0,4.0,4.0,0.0,4.0,0.0
37,248400335,CC Vaison Ventoux,Français par acquisition,4.0,0.0,32.0,4.0,4.0,4.0,4.0,...,4.0,0.0,0.0,0.0,0.0,4.0,0.0,4.0,4.0,0.0

#### Sauver en base

In [85]:
#save_to_database(result, 'INAT_NAT_EPCI', schema_name='imhana2021')

import pandas.io.sql as sql
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:postgres@localhost:5432/inseedb')
ORM_conn=engine.connect()
#ORM_conn

#result.to_postgis('NAT', con=ORM_conn , schema='imhana2021', if_exists='replace', index=False)
result.to_sql('INAT_NAT_EPCI', con=engine , schema='imhana2021', if_exists='replace', index=False)

ORM_conn.commit()
ORM_conn.close()

### Version 2 : on accole INAT à epci_nat

In [ ]:
datapath = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\\"
suffix = "_2026.01.22.csv"
epcisuffix = "_EPCI_2026.01.22.csv"

variable = 'INAT_BIS'
print(datapath)
nat_epci_file = datapath+'INAT'+"_NAT_EPCI"+suffix
#nat_epci_file = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\NAT_EPCI_2026.01.22.csv"

demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)

#unit == '248500191' and  
demo01 = demographie_etrangers.query("unit == '248500191' and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', variable], columns='NAT2', values='total_s')
demo02 = demographie_etrangers.query(" (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM', variable], columns='NAT2', values='total_s',aggfunc="max") 
demo03 = demographie_etrangers.query(" (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM', variable], columns='NAT2', values='total_s',aggfunc="sum") 


frames = [demo01, demo02, demo03]

result = pd.concat(frames)
result.fillna(0, inplace=True)
result.rename_axis(columns=None, inplace=True)
result.reset_index(inplace=True)

print(result.columns)
print(result.shape) #(1224, 6)

print(result)
database = result
#demographie_etrangers.query("unit == '248500191'").NAT2.unique().tolist() à la place liste_natio
database = result.melt(id_vars=['unit', 'NOM', variable], value_vars=liste_natio+nationalites_speciales, var_name=['NAT2'], value_name='total_s')
database = database.astype(dtype = {'unit': 'string', 'NOM': 'string', 'NAT2': 'string', 'total_s': 'int'})

print(database.shape) #(243576, 4)
print(database.columns) #['unit', 'NOM', 'NAT2', 'POPULATION_NAT2']
print(database.dtypes)
database

database = database.pivot(index=['unit', 'NOM', 'NAT2'], columns=variable, values='total_s')
database.rename_axis(columns=None, inplace=True)
database.reset_index(inplace=True)
print(database.shape) #(243576, 5) 
print(database.columns) #['unit', 'NOM', 'NAT2', 'Féminin', 'Masculin'] 
print(database.dtypes)
database

In [99]:
## Debug

demo01 = demographie_etrangers.query("unit == '248500191'  and NAT2 not in @nationalites_speciales and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', 'NAT2'], columns='INAT_BIS', values='total_s')
demo01

INAT_BIS                                                Etranger  \
unit      NOM                        NAT2
248500191 CC de l'Île de Noirmoutier Algériens               4.0
                                     Allemands               4.0
                                     Américains (U.S.)       4.0
                                     Angolais                NaN
                                     Argentins               4.0
                                     Arméniens               NaN
                                     Belges                 19.0
                                     Britanniques            4.0
                                     Brésiliens              NaN
                                     Bulgares                4.0
                                     Cambodgiens             4.0
                                     Chiliens                4.0
                                     Colombiens              NaN
                                     Danois                  4.0
                                     Espagnols               4.0
                                     Français                NaN
                                     Grecs                   NaN
                                     Guatémaltèques          NaN
                                     Indiens                 NaN
                                     Italiens                4.0
                                     Ivoiriens               4.0
                                     Malgaches               4.0
                                     Marocains               4.0
                                     Mauriciens              4.0
                                     Mexicains               NaN
                                     Néerlandais             4.0
                                     Pakistanais             4.0
                                     Philippins              4.0
                                     Polonais                NaN
                                     Portugais               4.0
                                     Roumains                NaN
                                     Russes                  NaN
                                     Rwandais                NaN
                                     Seychellois             4.0
                                     Sud-Africains           NaN
                                     Suisses                 NaN
                                     Surinamais              NaN
                                     Suédois                 4.0
                                     Sénégalais              4.0
                                     Tanzaniens              4.0
                                     Thaïlandais             4.0
                                     Tunisiens               4.0
                                     Ukrainiens              NaN
                                     Vietnamiens             NaN
                                     Zaïrois                 4.0

INAT_BIS                                                Français Guadeloupe (971)  \
unit      NOM                        NAT2
248500191 CC de l'Île de Noirmoutier Algériens                                NaN
                                     Allemands                                NaN
                                     Américains (U.S.)                        NaN
                                     Angolais                                 NaN
                                     Argentins                                NaN
                                     Arméniens                                NaN
                                     Belges                                   NaN
                                     Britanniques                             NaN
                                     Brésiliens                               NaN
                                     Bulgares                                 NaN
                                     Cambodgiens                              NaN
                                     Chiliens                                 NaN
                                     Colombiens                               NaN
                                     Danois                                   NaN
                                     Espagnols                                NaN
                                     Français                                 4.0
                                     Grecs                                    NaN
                                     Guatémaltèques                           NaN
                                     Indiens                                  NaN
                                     Italiens                                 NaN
                                     Ivoiriens                                NaN
                                     Malgaches                                NaN
                                     Marocains                                NaN
                                     Mauriciens                               NaN
                                     Mexicains                                NaN
                                     Néerlandais                              NaN
                                     Pakistanais                              NaN
                                     Philippins                               NaN
                                     Polonais                                 NaN
                                     Portugais                                NaN
                                     Roumains                                 NaN
                                     Russes                                   NaN
                                     Rwandais                                 NaN
                                     Seychellois                              NaN
                                     Sud-Africains                            NaN
                                     Suisses                                  NaN
                                     Surinamais                               NaN
                                     Suédois                                  NaN
                                     Sénégalais                               NaN
                                     Tanzaniens                               NaN
                                     Thaïlandais                              NaN
                                     Tunisiens                                NaN
                                     Ukrainiens                               NaN
                                     Vietnamiens                              NaN
                                     Zaïrois                                  NaN

INAT_BIS                                                Français Guyane (973)  \
unit      NOM                        NAT2
248500191 CC de l'Île de Noirmoutier Algériens                            NaN
                                     Allemands                            NaN
                                     Américains (U.S.)                    NaN
                                     Angolais                             NaN
                                     Argentins                            NaN
                                     Arméniens                            NaN
                                     Belges                               NaN
                                     Britanniques                         NaN
                                     Brésiliens                           NaN
                                     Bulgares                             NaN
                                     Cambodgiens                          NaN
                                     Chiliens                             NaN
                                     Colombiens                           NaN
                                     Danois                               NaN
                                     Espagnols                            NaN
                                     Français                             4.0
                                     Grecs                                NaN
                                     Guatémaltèques                       NaN
                                     Indiens                              NaN
                                     Italiens                             NaN
                                     Ivoiriens                            NaN
                                     Malgaches                            NaN
                                     Marocains                            NaN
                                     Mauriciens                           NaN
                                     Mexicains                            NaN
                                     Néerlandais                          NaN
                                     Pakistanais                          NaN
                                     Philippins                           NaN
                                     Polonais                             NaN
                                     Portugais                            NaN
                                     Roumains                             NaN
                                     Russes                               NaN
                                     Rwandais                             NaN
                                     Seychellois                          NaN
                                     Sud-Africains                        NaN
                                     Suisses                              NaN
                                     Surinamais                           NaN
                                     Suédois                              NaN
                                     Sénégalais                           NaN
                                     Tanzaniens                           NaN
                                     Thaïlandais                          NaN
                                     Tunisiens                            NaN
                                     Ukrainiens                           NaN
                                     Vietnamiens                          NaN
                                     Zaïrois                              NaN

INAT_BIS                                                Français La Réunion (974)  \
unit      NOM                        NAT2
248500191 CC de l'Île de Noirmoutier Algériens                                NaN
                                     Allemands                                NaN
                                     Américains (U.S.)                        NaN
                                     Angolais                                 NaN
                                     Argentins                                NaN
                                     Arméniens                                NaN
                                     Belges                                   NaN
                                     Britanniques                             NaN
                                     Brésiliens                               NaN
                                     Bulgares                                 NaN
                                     Cambodgiens                              NaN
                                     Chiliens                                 NaN
                                     Colombiens                               NaN
                                     Danois                                   NaN
                                     Espagnols                                NaN
                                     Français                                 4.0
                                     Grecs                                    NaN
                                     Guatémaltèques                           NaN
                                     Indiens                                  NaN
                                     Italiens                                 NaN
                                     Ivoiriens                                NaN
                                     Malgaches                                NaN
                                     Marocains                                NaN
                                     Mauriciens                               NaN
                                     Mexicains                                NaN
                                     Néerlandais                              NaN
                                     Pakistanais                              NaN
                                     Philippins                               NaN
                                     Polonais                                 NaN
                                     Portugais                                NaN
                                     Roumains                                 NaN
                                     Russes                                   NaN
                                     Rwandais                                 NaN
                                     Seychellois                              NaN
                                     Sud-Africains                            NaN
                                     Suisses                                  NaN
                                     Surinamais                               NaN
                                     Suédois                                  NaN
                                     Sénégalais                               NaN
                                     Tanzaniens                               NaN
                                     Thaïlandais                              NaN
                                     Tunisiens                                NaN
                                     Ukrainiens                               NaN
                                     Vietnamiens                              NaN
                                     Zaïrois                                  NaN

INAT_BIS                                                Français Martinique (972)  \
unit      NOM                        NAT2
248500191 CC de l'Île de Noirmoutier Algériens                                NaN
                                     Allemands                                NaN
                                     Américains (U.S.)                        NaN
                                     Angolais                                 NaN
                                     Argentins                                NaN
                                     Arméniens                                NaN
                                     Belges                                   NaN
                                     Britanniques                             NaN
                                     Brésiliens                               NaN
                                     Bulgares                                 NaN
                                     Cambodgiens                              NaN
                                     Chiliens                                 NaN
                                     Colombiens                               NaN
                                     Danois                                   NaN
                                     Espagnols                                NaN
                                     Français                                 4.0
                                     Grecs                                    NaN
                                     Guatémaltèques                           NaN
                                     Indiens                                  NaN
                                     Italiens                                 NaN
                                     Ivoiriens                                NaN
                                     Malgaches                                NaN
                                     Marocains                                NaN
                                     Mauriciens                               NaN
                                     Mexicains                                NaN
                                     Néerlandais                              NaN
                                     Pakistanais                              NaN
                                     Philippins                               NaN
                                     Polonais                                 NaN
                                     Portugais                                NaN
                                     Roumains                                 NaN
                                     Russes                                   NaN
                                     Rwandais                                 NaN
                                     Seychellois                              NaN
                                     Sud-Africains                            NaN
                                     Suisses                                  NaN
                                     Surinamais                               NaN
                                     Suédois                                  NaN
                                     Sénégalais                               NaN
                                     Tanzaniens                               NaN
                                     Thaïlandais                              NaN
                                     Tunisiens                                NaN
                                     Ukrainiens                               NaN
                                     Vietnamiens                              NaN
                                     Zaïrois                                  NaN

INAT_BIS                                                Français Metropole  \
unit      NOM                        NAT2
248500191 CC de l'Île de Noirmoutier Algériens                         NaN
                                     Allemands                         NaN
                                     Américains (U.S.)                 NaN
                                     Angolais                          NaN
                                     Argentins                         NaN
                                     Arméniens                         NaN
                                     Belges                            NaN
                                     Britanniques                      NaN
                                     Brésiliens                        NaN
                                     Bulgares                          NaN
                                     Cambodgiens                       NaN
                                     Chiliens                          NaN
                                     Colombiens                        NaN
                                     Danois                            NaN
                                     Espagnols                         NaN
                                     Français                       9040.0
                                     Grecs                             NaN
                                     Guatémaltèques                    NaN
                                     Indiens                           NaN
                                     Italiens                          NaN
                                     Ivoiriens                         NaN
                                     Malgaches                         NaN
                                     Marocains                         NaN

### version 2 INAT long ok

In [ ]:
unit == '248500191'  and
nat_epci_file = datapath+"INAT_NAT"+epcisuffix
demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)
    
demo01 = demographie_etrangers.query("  NAT2 not in @nationalites_speciales and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', 'NAT2'], columns='INAT_BIS', values='total_s')
demo02 = demographie_etrangers.query(" NAT2 not in @nationalites_speciales and (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM', 'NAT2'], columns='INAT_BIS', values='total_s',aggfunc="max") 
demo03 = demographie_etrangers.query(" NAT2 not in @nationalites_speciales and (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM', 'NAT2'], columns='INAT_BIS', values='total_s',aggfunc="sum") 
    
#print(FRENCH_DOMTOM)

frames = [demo01, demo02, demo03]

result = pd.concat(frames)

result.fillna(0, inplace=True)
result.rename_axis(columns=None, inplace=True)
result.reset_index(inplace=True)

#result.loc[result.NAT2.isin([ 'Tous', 'immigres'])]
result.loc[result.NAT2.isin(['Algériens', 'Français'])] 

#Rajouter une colonne  Français de naissance  
result['Français de naissance'] = result[FRENCH_DOMTOM].sum(axis=1)

result = result[['unit', 'NOM', 'NAT2', 'Etranger', 'Français par acquisition', 'Français de naissance'] + [col for col in result.columns if col not in ['unit', 'NOM', 'NAT2', 'Etranger', 'Français par acquisition', 'Français de naissance']]]

map_columnsTypes = {'Etranger': 'int', 'Français par acquisition': 'int', 'Français de naissance': 'int'}
for f in FRENCH_DOMTOM:
    map_columnsTypes[f] = 'int'
print(map_columnsTypes)
result = result.astype(dtype = map_columnsTypes)

print(result.columns)
print(result.shape) #(96033, 18)

# Vérifier
result.loc[result.NAT2.isin(['Algériens', 'Français'])] 

###STOP - inutile si on fusionne avec NAT après

# database_long = result[['unit']]
# database_long['anneeRp'] =  2021
# database_long['indicateur'] =  'NAT' #servira de PK avec unit, et anneeRp et permettra de faire le lien avec les autres indicateurs
# database_long['indicateurCode'] =  'NAT2' 
# database_long['indicateurMode'] =  '' 
# database_long['NAT2'] =  result[['NAT2']] 

# database_long = pd.merge(database_long, result, on=['unit', 'NAT2'], how='left') 
# print(database_long.shape) #(96033, 22)

# database_long.loc[result.NAT2.isin(['Algériens', 'Français'])] #(96033, 22)

,unit,NOM,Tous,etrangers,francaisParAcquisition,immigres
0,200000172,CC Faucigny-Glières,27764,2382,1789,3543
1,200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,36232,311,297,528
2,200000545,CC des Portes de Romilly-sur-Seine,18866,2065,1331,2787
3,200000628,CC Rhône Lez Provence,24003,1626,1236,2338
4,200000800,CC Cour de Sologne,10310,278,264,451
...,...,...,...,...,...,...
1219,243500741,CA Redon Agglomération,66837,1261,659,1666
1220,244400610,CA de la Presqu'île de Guérande Atlantique (Ca...,76565,850,910,1521
1221,246100663,CU d'Alençon,55435,2801,1476,3727
1222,247600588,CC des Villes Sours,35817,247,269,430
1223,248400251,CA du Grand Avignon (COGA),194858,18851,12941,27168

In [131]:
NAT2_DECOMPOSITION = ['Etranger', 'Français par acquisition', 'Français de naissance']+ FRENCH_DOMTOM.tolist()
NAT2_DECOMPOSITION

['Etranger',
 'Français par acquisition',
 'Français de naissance',
 'Français Guadeloupe (971)',
 'Français Guyane (973)',
 'Français La Réunion (974)',
 'Français Martinique (972)',
 'Français Mayotte (976)',
 'Français Metropole',
 'Français Nouvelle-Calédonie (988)',
 'Français Polynésie Française (987)',
 'Français Saint-Martin (978)',
 'Français Saint-Pierre-et-Miquelon (975)',
 'Français Wallis et Futuna (986)',
 'Français Saint-Barthélemy (977)']

In [ ]:
nationalites_speciales # ['Tous', 'etrangers', 'francaisParAcquisition', 'immigres']
len(pd.unique(result.NAT2)) #195
len(liste_natio) #195

195

## Lire avec Gen2 ou IMMI

In [151]:
nat_epci_file = datapath+"GEN2_NAT"+epcisuffix
demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)

demo01 = demographie_etrangers.query(" NAT2 not in @nationalites_speciales and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', 'NAT2'], columns='GENERATION2', values='total_s')
demo02 = demographie_etrangers.query(" NAT2 not in @nationalites_speciales and (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM', 'NAT2'], columns='GENERATION2', values='total_s',aggfunc="max") 
demo03 = demographie_etrangers.query(" NAT2 not in @nationalites_speciales and (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM', 'NAT2'], columns='GENERATION2', values='total_s',aggfunc="sum") 
    
frames = [demo01, demo02, demo03]
result = pd.concat(frames)

result.fillna(0, inplace=True)
result.rename_axis(columns=None, inplace=True)
result.reset_index(inplace=True)

print(result.columns)
# Renommer True en SecondeGeneration - étranger né en France 
# SecondeGeneration: les étrangers (INAT = 21) ou francais naturalisés (INAT = 12) nés en France (donc non immigrés)
# GENERATION2 = ifelse(INAT!=11 & IMMI==2, TRUE, FALSE)
result.rename(columns={True:'SecondeGeneration', False:'PremiereGeneration'}, inplace=True)


# #Réordonner les colonnes et retirer NOM
result = result[['unit', 'NAT2', 'SecondeGeneration', 'PremiereGeneration'] ]


# print(result.columns)
print(result.shape) #(96033, 18)
result.loc[result.NAT2.isin(['Algériens', 'Français'])]

Index(['unit', 'NOM', 'NAT2', False, True], dtype='object')
(96033, 4)

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\2533033509.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')

            unit       NAT2  SecondeGeneration  PremiereGeneration
1      200000172  Algériens               33.0               310.0
33     200000172   Français                0.0             23593.0
97     200000438  Algériens                4.0                16.0
125    200000438   Français                0.0             35624.0
172    200000545  Algériens               55.0               264.0
...          ...        ...                ...                 ...
95771  246100663   Français                0.0             51158.0
95836  247600588  Algériens                8.0                20.0
95856  247600588   Français                0.0             35301.0
95899  248400251  Algériens              438.0              3705.0
95945  248400251   Français                0.0            163067.0

[2445 rows x 4 columns]

In [152]:
nat_epci_file = datapath+"IMMI_NAT"+epcisuffix
demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)

demo01 = demographie_etrangers.query(" NAT2 not in @nationalites_speciales and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', 'NAT2'], columns='IMMI', values='total_s')
demo02 = demographie_etrangers.query(" NAT2 not in @nationalites_speciales and (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM', 'NAT2'], columns='IMMI', values='total_s',aggfunc="max") 
demo03 = demographie_etrangers.query(" NAT2 not in @nationalites_speciales and (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM', 'NAT2'], columns='IMMI', values='total_s',aggfunc="sum") 
    
frames = [demo01, demo02, demo03]
result = pd.concat(frames)

result.fillna(0, inplace=True)
result.rename_axis(columns=None, inplace=True)
result.reset_index(inplace=True)

print(result.columns)

# Réordonner les colonnes et retirer NOM
result = result[['unit', 'NAT2', 'Immigrés', 'Non immigrés'] ]

# print(result.columns)
print(result.shape) #(96033, 18)
result.loc[result.NAT2.isin(['Algériens', 'Français'])]

Index(['unit', 'NOM', 'NAT2', 'Immigrés', 'Non immigrés'], dtype='object')
(96033, 4)

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\3523167711.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')

            unit       NAT2  Immigrés  Non immigrés
1      200000172  Algériens     310.0          33.0
33     200000172   Français       0.0       23593.0
97     200000438  Algériens      16.0           4.0
125    200000438   Français       0.0       35624.0
172    200000545  Algériens     264.0          55.0
...          ...        ...       ...           ...
95771  246100663   Français       0.0       51158.0
95836  247600588  Algériens      20.0           8.0
95856  247600588   Français       0.0       35301.0
95899  248400251  Algériens    3705.0         438.0
95945  248400251   Français       0.0      163067.0

[2445 rows x 4 columns]

## Lire avec INAT et SEXE

#### lire NAT avec SEXE

In [169]:
variable = 'SEXE'
nat_epci_file = datapath+variable+"_NAT_EPCI"+suffix
#nat_epci_file = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\NAT_EPCI_2026.01.22.csv"

demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)

#unit == '248500191' and  
demo01 = demographie_etrangers.query("NAT2 not in @nationalites_speciales and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', variable], columns='NAT2', values='total_s')
demo02 = demographie_etrangers.query("NAT2 not in @nationalites_speciales and (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM', variable], columns='NAT2', values='total_s',aggfunc="max") 
demo03 = demographie_etrangers.query("NAT2 not in @nationalites_speciales and (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM', variable], columns='NAT2', values='total_s',aggfunc="sum") 


frames = [demo01, demo02, demo03]

result = pd.concat(frames)
result.fillna(0, inplace=True)
result.rename_axis(columns=None, inplace=True)
result.reset_index(inplace=True)

print(result.columns)
print(result.shape) #(2448, 198)

result

# #demographie_etrangers.query("unit == '248500191'").NAT2.unique().tolist() à la place liste_natio
database = result.melt(id_vars=['unit', 'NOM', variable], value_vars=liste_natio, var_name=['NAT2'], value_name='total_s')
database = database.astype(dtype = {'unit': 'string', 'NOM': 'string', 'NAT2': 'string', 'total_s': 'int'})
database.rename(columns={variable : 'indicateurMode', 'total_s':'Ensemble'}, inplace=True)

print(database.shape) #(477360, 5)
print(database.columns) #['unit', 'NOM', 'indicateurMode', 'NAT2', 'Ensemble']
print(database.dtypes)
database

database['anneeRp']  = 2021
database['indicateur']  = variable
database['indicateurCode']  = variable
    

print(database.shape) #(243576, 8) 
print(database.columns) #['unit', 'NOM', 'indicateurMode', 'NAT2', 'Ensemble', 'anneeRp', 'indicateur', 'indicateurCode']
print(database.dtypes)
#database.loc[database.Ensemble > 16]
database[['unit', 'NAT2', 'anneeRp', 'indicateur', 'indicateurCode', 'indicateurMode',  'Ensemble' ]].loc[database.Ensemble > 16]

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\308787556.py:5: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')

Index(['unit', 'NOM', 'SEXE', 'Afghans', 'Albanais', 'Algériens', 'Allemands',
       'Américains (U.S.)', 'Andorrans', 'Angolais',
       ...
       'Tuvaluans', 'Ukrainiens', 'Uruguayens', 'Vanuatuans', 'Vietnamiens',
       'Vénézuéliens', 'Yéménites', 'Zambiens', 'Zaïrois', 'Zimbabwéens'],
      dtype='object', length=198)
(2448, 198)
(477360, 5)
Index(['unit', 'NOM', 'indicateurMode', 'NAT2', 'Ensemble'], dtype='object')
unit              string
NOM               string
indicateurMode    object
NAT2              string
Ensemble           int32
dtype: object
(477360, 8)
Index(['unit', 'NOM', 'indicateurMode', 'NAT2', 'Ensemble', 'anneeRp',
       'indicateur', 'indicateurCode'],
      dtype='object')
unit              string
NOM               string
indicateurMode    object
NAT2              string
Ensemble           int32
anneeRp            int64
indicateur        object
indicateurCode    object
dtype: object

,unit,NAT2,anneeRp,indicateur,indicateurCode,indicateurMode,Ensemble
31,200010650,Afghans,2021,SEXE,SEXE,Masculin,40
33,200010700,Afghans,2021,SEXE,SEXE,Masculin,29
47,200017846,Afghans,2021,SEXE,SEXE,Masculin,57
63,200023240,Afghans,2021,SEXE,SEXE,Masculin,32
70,200023414,Afghans,2021,SEXE,SEXE,Féminin,120
...,...,...,...,...,...,...,...
438706,200054781,Nord-Coréens,2021,SEXE,SEXE,Féminin,37
438707,200054781,Nord-Coréens,2021,SEXE,SEXE,Masculin,29
443603,200054781,Qatariens,2021,SEXE,SEXE,Masculin,23
443757,200066868,Qatariens,2021,SEXE,SEXE,Masculin,24
444797,243300316,Qatariens,2021,SEXE,SEXE,Masculin,20

#### Lire INAT, GEN2, IMMI avec SEXE

In [ ]:
variable = 'SEXE'
croix = 'GEN2'
correspondances = {'INAT':'INAT_BIS', 'GEN2' : 'GENERATION2', 'IMMI' : 'IMMI'}

### INAT
nat_epci_file = datapath+variable+"_"+croix+"_NAT_EPCI"+suffix
#nat_epci_file = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\NAT_EPCI_2026.01.22.csv"

demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)

#unit == '248500191' and  
demo01 = demographie_etrangers.query("NAT2 not in @nationalites_speciales and not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', 'NAT2', variable], columns=correspondances[croix], values='total_s')
demo02 = demographie_etrangers.query("NAT2 not in @nationalites_speciales and (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM', 'NAT2', variable], columns=correspondances[croix], values='total_s',aggfunc="max") 
demo03 = demographie_etrangers.query("NAT2 not in @nationalites_speciales and (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM', 'NAT2', variable], columns=correspondances[croix], values='total_s',aggfunc="sum") 

frames = [demo01, demo02, demo03]
result = pd.concat(frames)

result.fillna(0, inplace=True)
result.rename_axis(columns=None, inplace=True)
result.reset_index(inplace=True)

# renommer la colonne variable par indicateurMode 
result.rename(columns={variable : 'indicateurMode'}, inplace=True)

if (croix == 'INAT') :
    #Rajouter une colonne Français de naissance
    result['Français de naissance'] = result[FRENCH_DOMTOM].sum(axis=1)
    #Réordonner les colonnes, et retirer NOM
    result = result[['unit', 'NAT2', 'indicateurMode', 'Etranger', 'Français par acquisition', 'Français de naissance'] + [col for col in result.columns if col not in ['unit', 'NOM', 'NAT2', 'indicateurMode', 'Etranger', 'Français par acquisition', 'Français de naissance']]]
if (croix ==  'GEN2') : 
    result.rename(columns={True:'SecondeGeneration', False:'PremiereGeneration'}, inplace=True)
    # retirer NOM des colonnes
    result = result[['unit', 'NAT2', 'indicateurMode', 'SecondeGeneration', 'PremiereGeneration'] ]
if (croix ==  'IMMI') : 
    # retirer NOM des colonnes
    result = result[['unit', 'NAT2', 'indicateurMode', 'Immigrés', 'Non immigrés'] ]
    
print(result.columns)
print(result.shape) #(157960, 18)

result

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\3330392659.py:5: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')

Index(['unit', 'NAT2', 'indicateurMode', 'Etranger',
       'Français par acquisition', 'Français de naissance',
       'Français Guadeloupe (971)', 'Français Guyane (973)',
       'Français La Réunion (974)', 'Français Martinique (972)',
       'Français Mayotte (976)', 'Français Metropole',
       'Français Nouvelle-Calédonie (988)',
       'Français Polynésie Française (987)', 'Français Saint-Barthélemy (977)',
       'Français Saint-Martin (978)',
       'Français Saint-Pierre-et-Miquelon (975)',
       'Français Wallis et Futuna (986)'],
      dtype='object')
(157960, 18)

,unit,NAT2,indicateurMode,Etranger,Français par acquisition,Français de naissance,Français Guadeloupe (971),Français Guyane (973),Français La Réunion (974),Français Martinique (972),Français Mayotte (976),Français Metropole,Français Nouvelle-Calédonie (988),Français Polynésie Française (987),Français Saint-Barthélemy (977),Français Saint-Martin (978),Français Saint-Pierre-et-Miquelon (975),Français Wallis et Futuna (986)
0,200000172,Albanais,Féminin,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,200000172,Albanais,Masculin,31.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,200000172,Algériens,Féminin,75.0,94.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,200000172,Algériens,Masculin,69.0,106.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,200000172,Allemands,Féminin,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157955,248400251,Vénézuéliens,Féminin,4.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
157956,248400251,Vénézuéliens,Masculin,17.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
157957,248400251,Zaïrois,Féminin,4.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
157958,248400251,Zaïrois,Masculin,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
157959,248400251,Zimbabwéens,Féminin,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [141]:

engine = create_engine('postgresql://postgres:postgres@localhost:5432/inseedb')
ORM_conn=engine.connect()
database_long.to_sql('inat_nat', con=ORM_conn , schema='imhana2021', if_exists='replace', index=False)
ORM_conn.commit()
ORM_conn.close()

## Lire NAT2 et SEXE par exemple

In [103]:
nat_epci_file = datapath+"SEXE_NAT_EPCI"+suffix
#nat_epci_file = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\NAT_EPCI_2026.01.22.csv"

demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)

#unit == '248500191' and  
demo01 = demographie_etrangers.query("not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', 'SEXE'], columns='NAT2', values='total_s')
demo02 = demographie_etrangers.query(" (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM', 'SEXE'], columns='NAT2', values='total_s',aggfunc="max") 
demo03 = demographie_etrangers.query(" (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM', 'SEXE'], columns='NAT2', values='total_s',aggfunc="sum") 


frames = [demo01, demo02, demo03]

result = pd.concat(frames)
result.fillna(0, inplace=True)
result.rename_axis(columns=None, inplace=True)
result.reset_index(inplace=True)

print(result.columns)
print(result.shape) #(1224, 6)

print(result)
database = result
#demographie_etrangers.query("unit == '248500191'").NAT2.unique().tolist() à la place liste_natio
database = result.melt(id_vars=['unit', 'NOM', 'SEXE'], value_vars=liste_natio+nationalites_speciales, var_name=['NAT2'], value_name='total_s')
database = database.astype(dtype = {'unit': 'string', 'NOM': 'string', 'NAT2': 'string', 'total_s': 'int'})
#database.rename(columns={'total_s':'SEXE_NAT2'}, inplace=True)

print(database.shape) #(243576, 4)
print(database.columns) #['unit', 'NOM', 'NAT2', 'POPULATION_NAT2']
print(database.dtypes)
database

database = database.pivot(index=['unit', 'NOM', 'NAT2'], columns='SEXE', values='total_s')
database.rename_axis(columns=None, inplace=True)
database.reset_index(inplace=True)
print(database.shape) #(243576, 5) 
print(database.columns) #['unit', 'NOM', 'NAT2', 'Féminin', 'Masculin'] 
print(database.dtypes)
database

modalites_variables = database.columns[3:].tolist()
modalites_variables

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_47832\1158057707.py:4: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')

Index(['unit', 'NOM', 'SEXE', 'Afghans', 'Albanais', 'Algériens', 'Allemands',
       'Américains (U.S.)', 'Andorrans', 'Angolais',
       ...
       'Vanuatuans', 'Vietnamiens', 'Vénézuéliens', 'Yéménites', 'Zambiens',
       'Zaïrois', 'Zimbabwéens', 'etrangers', 'francaisParAcquisition',
       'immigres'],
      dtype='object', length=202)
(2448, 202)
           unit                                              NOM      SEXE  \
0     200000172                              CC Faucigny-Glières   Féminin
1     200000172                              CC Faucigny-Glières  Masculin
2     200000438  CC du Pays de Pontchâteau Saint-Gildas-des-Bois   Féminin
3     200000438  CC du Pays de Pontchâteau Saint-Gildas-des-Bois  Masculin
4     200000545               CC des Portes de Romilly-sur-Seine   Féminin
...         ...                                              ...       ...
2443  246100663                                     CU d'Alençon  Masculin
2444  247600588                              CC des Villes Sours   Féminin
2445  247600588                              CC des Villes Sours  Masculin
2446  248400251                       CA du Grand Avignon (COGA)   Féminin
2447  248400251                       CA du Grand Avignon (COGA)  Masculin

      Afghans  Albanais  Algériens  Allemands  Américains (U.S.)  Andorrans  \
0         0.0       4.0      168.0        4.0                4.0        0.0
1         0.0      31.0      175.0        4.0                4.0        0.0
2         0.0       4.0        4.0        4.0                4.0        0.0
3         4.0       0.0        4.0        4.0                4.0        0.0
4         0.0       0.0      181.0        4.0                4.0        0.0
...       ...       ...        ...        ...                ...        ...
2443     75.0       4.0      132.0       22.0                4.0        0.0
2444      0.0       0.0        8.0        8.0                8.0        0.0
2445      0.0       0.0        8.0        4.0                8.0        0.0
2446     34.0       8.0     2248.0      200.0               57.0        4.0
2447    111.0      32.0     1900.0      104.0               44.0        0.0

      Angolais  ...  Vanuatuans  Vietnamiens  Vénézuéliens  Yéménites  \
0          0.0  ...         0.0         43.0           0.0        0.0
1          4.0  ...         0.0         45.0           4.0        0.0
2          0.0  ...         0.0          4.0           0.0        0.0
3          0.0  ...         0.0          4.0           4.0        0.0
4          4.0  ...         0.0         19.0           0.0        0.0
...        ...  ...         ...          ...           ...        ...
2443       4.0  ...         0.0         31.0           0.0        0.0
2444       0.0  ...         0.0          4.0           0.0        0.0
2445       0.0  ...         0.0          4.0           0.0        0.0
2446       4.0  ...         0.0        164.0          24.0        0.0
2447       4.0  ...         0.0        153.0          19.0        0.0

      Zambiens  Zaïrois  Zimbabwéens  etrangers  francaisParAcquisition  \
0          0.0      4.0          0.0     1152.0                   948.0
1          0.0      4.0          0.0     1230.0                   841.0
2          0.0      0.0          0.0      139.0                   170.0
3          0.0      4.0          0.0      171.0                   127.0
4          0.0     17.0          0.0     1134.0                   690.0
...        ...      ...          ...        ...                     ...
2443       0.0     53.0          0.0     1508.0                   776.0
2444       0.0      0.0          0.0      133.0                   145.0
2445       0.0      0.0          0.0      113.0                   124.0
2446       0.0      8.0          4.0     9533.0                  6698.0
2447       0.0      8.0          0.0     9318.0                  6243.0

      immigres
0       1782.0
1       1761.0
2        273.0
3        255.0
4       1509.0
...        ...
2443    1996.0
2444     239.0
2445     192.0
2446   13933.0
2447   13235.0

[2448 rows x 202 columns]
(487152, 5)
Index(['unit', 'NOM', 'SEXE', 'NAT2', 'total_s'], dtype='object')
unit       string
NOM        string
SEXE       object
NAT2       string
total_s     int32
dtype: object
(243576, 5)
Index(['unit', 'NOM', 'NAT2', 'Féminin', 'Masculin'], dtype='object')
unit        string
NOM         string
NAT2        string
Féminin      int32
Masculin     int32
dtype: object

['Féminin', 'Masculin']

In [ ]:
demographie_etrangers.query("unit == '248500191'").NAT2.unique().tolist()+nationalites_speciales

ValueError: operands could not be broadcast together with shapes (49,) (4,)

In [86]:
print(liste_natio+nationalites_speciales) # Français
for i in liste_natio+nationalites_speciales:
    #print(i)
    if i.startswith('Français'):
        print(i)

['Afghans', 'Albanais', 'Algériens', 'Allemands', 'Américains (U.S.)', 'Angolais', 'Arméniens', 'Australiens', 'Autrichiens', 'Belges', 'Bissao-Guinéens', 'Biélorusses', 'Bosniaques', 'Britanniques', 'Brésiliens', 'Bulgares', 'Burkinabés', 'Burundais', 'Béninois', 'Cambodgiens', 'Camerounais', 'Canadiens', 'Cap-Verdiens', 'Centrafricains', 'Chiliens', 'Chinois', 'Colombiens', 'Comoriens', 'Congolais', 'Cubains', 'Danois', 'Dominicains', 'Dominiquais', 'Egyptiens', 'Equatoriens', 'Espagnols', 'Ethiopiens', 'Fidjiens', 'Français', 'Gabonais', 'Ghanéens', 'Grecs', 'Guatémaltèques', 'Guinéens', 'Haïtiens', 'Hongrois', 'Indiens', 'Indonésiens', 'Iraniens', 'Irlandais', 'Israéliens', 'Italiens', 'Ivoiriens', 'Japonais', 'Jordaniens', 'Libanais', 'Libyens', 'Lituaniens', 'Luxembourgeois', 'Malaisiens', 'Malgaches', 'Maliens', 'Marocains', 'Mauriciens', 'Mauritaniens', 'Mexicains', 'Monténégrins', 'Nigérians', 'Nigériens', 'Néerlandais', 'Népalais', 'Pakistanais', 'Palestiniens', 'Paraguayens', 'Philippins', 'Polonais', 'Portugais', 'Péruviens', 'Roumains', 'Russes', 'Saint-Luciens', 'Serbes', 'Slovaques', 'Somaliens', 'Soudanais (2010)', 'Sri-Lankais', 'Sud-Africains', 'Sud-Coréens', 'Suisses', 'Surinamais', 'Suédois', 'Syriens', 'Sénégalais', 'Tchèques', 'Thaïlandais', 'Togolais', 'Tunisiens', 'Turcs', 'Ukrainiens', 'Uruguayens', 'Vietnamiens', 'Vénézuéliens', 'Zaïrois', 'Croates', 'Honduriens', 'Moldaves', 'Néo-Zélandais', 'Sierra-Léonais', 'Tchadiens', 'Argentins', 'Bangladais', 'Djiboutiens', 'Laotiens', 'Finlandais', 'Géorgiens', 'Iraquiens', 'Jamaïcains', 'Lettons', 'Libériens', 'Panaméens', 'Seychellois', 'Yéménites', 'Zimbabwéens', 'Erythréens', 'Sahariens', 'Boliviens', 'Gambiens', 'Kényans', 'Mongols', 'Mozambicains', 'Rwandais', 'Slovènes', 'Maltais', 'Ouzbeks', 'Azerbaïdjanais', 'Chypriotes', 'Kazakhs', 'Macédoniens', 'Norvégiens', 'Singapouriens', 'Monégasques', 'Tonguiens', 'Turkmènes', 'Birmans', 'Costaricains', 'Barbadiens', 'Guyaniens', 'Andorrans', 'Nicaraguayens', 'Papouan neo guinéens', 'Trinidadiens', 'Koweïtiens', 'Ougandais', 'Saint-Marinais', 'Saoudiens', 'Taiwanais', 'Liechtensteinois', 'Vanuatuans', 'Maldiviens', 'Salvadoriens', 'Estoniens', 'Islandais', 'Tanzaniens', 'Zambiens', 'Bhoutanais', 'Santoméens', 'Tadjiks', 'Equato-Guinéens', 'Kirghiz', 'Antiguais et Barbudiens', 'Namibiens', 'Botswanéens', 'Emiriens', 'Brunéiens', 'Saint-Vincentais et Grenadins', 'Samoans', 'Grenadiens', 'Malawiens', 'Micronésiens', 'Nord-Coréens', 'Omanais', 'Qatariens', 'Sud-soudanais', 'Swazis', 'Salomonais', 'Bahamiens', 'Bahreïniens', 'Béliziens', 'Lesothans', 'Nauruans', 'Palauans', 'Timoriens', 'Tuvaluans', 'Kittitiens et Néviciens', 'Marshallais', 'Tous', 'etrangers', 'francaisParAcquisition', 'immigres']
Français

In [61]:
variable = 'SEXE'
nat_epci_file = datapath+variable+"_NAT"+epcisuffix
#nat_epci_file = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\NAT_EPCI_2026.01.22.csv"

demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)

#unit == '248500191' and  
demo01 = demographie_etrangers.query("not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', variable], columns='NAT2', values='total_s')
demo02 = demographie_etrangers.query(" (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM', variable], columns='NAT2', values='total_s',aggfunc="max") 
demo03 = demographie_etrangers.query(" (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM', variable], columns='NAT2', values='total_s',aggfunc="sum") 


frames = [demo01, demo02, demo03]

result = pd.concat(frames)
result.fillna(0, inplace=True)
result.rename_axis(columns=None, inplace=True)
result.reset_index(inplace=True)

print(result.columns)
print(result.shape) #(1224, 6)

result

Index(['unit', 'NOM', 'SEXE', 'Afghans', 'Albanais', 'Algériens', 'Allemands',
       'Américains (U.S.)', 'Andorrans', 'Angolais',
       ...
       'Vanuatuans', 'Vietnamiens', 'Vénézuéliens', 'Yéménites', 'Zambiens',
       'Zaïrois', 'Zimbabwéens', 'etrangers', 'francaisParAcquisition',
       'immigres'],
      dtype='object', length=202)
(2448, 202)

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\3160049128.py:5: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')

,unit,NOM,SEXE,Afghans,Albanais,Algériens,Allemands,Américains (U.S.),Andorrans,Angolais,...,Vanuatuans,Vietnamiens,Vénézuéliens,Yéménites,Zambiens,Zaïrois,Zimbabwéens,etrangers,francaisParAcquisition,immigres
0,200000172,CC Faucigny-Glières,Féminin,0.0,4.0,168.0,4.0,4.0,0.0,0.0,...,0.0,43.0,0.0,0.0,0.0,4.0,0.0,1152.0,948.0,1782.0
1,200000172,CC Faucigny-Glières,Masculin,0.0,31.0,175.0,4.0,4.0,0.0,4.0,...,0.0,45.0,4.0,0.0,0.0,4.0,0.0,1230.0,841.0,1761.0
2,200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,Féminin,0.0,4.0,4.0,4.0,4.0,0.0,0.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,139.0,170.0,273.0
3,200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,Masculin,4.0,0.0,4.0,4.0,4.0,0.0,0.0,...,0.0,4.0,4.0,0.0,0.0,4.0,0.0,171.0,127.0,255.0
4,200000545,CC des Portes de Romilly-sur-Seine,Féminin,0.0,0.0,181.0,4.0,4.0,0.0,4.0,...,0.0,19.0,0.0,0.0,0.0,17.0,0.0,1134.0,690.0,1509.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2443,246100663,CU d'Alençon,Masculin,75.0,4.0,132.0,22.0,4.0,0.0,4.0,...,0.0,31.0,0.0,0.0,0.0,53.0,0.0,1508.0,776.0,1996.0
2444,247600588,CC des Villes Sours,Féminin,0.0,0.0,8.0,8.0,8.0,0.0,0.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,133.0,145.0,239.0
2445,247600588,CC des Villes Sours,Masculin,0.0,0.0,8.0,4.0,8.0,0.0,0.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,113.0,124.0,192.0
2446,248400251,CA du Grand Avignon (COGA),Féminin,34.0,8.0,2248.0,200.0,57.0,4.0,4.0,...,0.0,164.0,24.0,0.0,0.0,8.0,4.0,9533.0,6698.0,13933.0
2447,248400251,CA du Grand Avignon (COGA),Masculin,111.0,32.0,1900.0,104.0,44.0,0.0,4.0,...,0.0,153.0,19.0,0.0,0.0,8.0,0.0,9318.0,6243.0,13235.0

In [ ]:
def process_niveau1_EPCI_wide(variable = 'SEXE'):
    nat_epci_file = datapath+variable+"_NAT"+epcisuffix
    #nat_epci_file = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\NAT_EPCI_2026.01.22.csv"

    demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
    demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)

    #unit == '248500191' and  
    demo01 = demographie_etrangers.query("not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', variable], columns='NAT2', values='total_s')
    demo02 = demographie_etrangers.query(" (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM', variable], columns='NAT2', values='total_s',aggfunc="max") 
    demo03 = demographie_etrangers.query(" (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM', variable], columns='NAT2', values='total_s',aggfunc="sum") 

    frames = [demo01, demo02, demo03]

    result = pd.concat(frames)
    result.fillna(0, inplace=True)
    result.rename_axis(columns=None, inplace=True)
    result.reset_index(inplace=True)

    print(result.columns)
    print(result.shape) #(1224, 6)

    database_wide = result[['unit']]
    database_wide['anneeRp'] =  2021
    database_wide['indicateur'] =  variable #servira de PK avec unit, et anneeRp et permettra de faire le lien avec les autres indicateurs
    database_wide['indicateurCode'] =  variable 
    database_wide['indicateurMode'] =  result[[variable]]
    database_wide['categorie'] = 'Ensemble' #	Etrangers, Français par acquisition,  SecondeGénération, Immigrés	

    result['indicateurMode']=  result[['SEXE']]
    database_wide = pd.merge(database_wide, result, on=['unit', 'indicateurMode'], how='left') 
    database_wide.drop(columns=['NOM', 'SEXE'], inplace=True)
    print(database_wide.shape)
    #(1224, 206) avec les 4 colonnes de unit, anneeRp, indicateur, indicateurCode, indicateurMode, categorie, et les 197 colonnes de nationalités, 'Tous' puis 'etrangers', 'francaisParAcquisition', 'immigres')

    return  database_wide

In [59]:
database_wide = process_niveau1_EPCI_wide(variable = 'SEXE')
database_wide

Index(['unit', 'NOM', 'SEXE', 'Afghans', 'Albanais', 'Algériens', 'Allemands',
       'Américains (U.S.)', 'Andorrans', 'Angolais',
       ...
       'Vanuatuans', 'Vietnamiens', 'Vénézuéliens', 'Yéménites', 'Zambiens',
       'Zaïrois', 'Zimbabwéens', 'etrangers', 'francaisParAcquisition',
       'immigres'],
      dtype='object', length=202)
(2448, 202)
(2448, 205)

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\2079649447.py:5: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\2079649447.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['anneeRp'] =  2021
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\2079649447.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['indicateur'] =  'NAT' #servira de PK avec unit, et anneeRp et permettra de faire le lien avec les autres indicateurs
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\2079649447.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['indicateurCode'] =  variable
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\2079649447.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['indicateurMode'] =  result[[variable]]
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\2079649447.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['categorie'] = 'Ensemble' #	Etrangers, Français par acquisition,  SecondeGénération, Immigrés

,unit,anneeRp,indicateur,indicateurCode,indicateurMode,categorie,Afghans,Albanais,Algériens,Allemands,...,Vanuatuans,Vietnamiens,Vénézuéliens,Yéménites,Zambiens,Zaïrois,Zimbabwéens,etrangers,francaisParAcquisition,immigres
0,200000172,2021,NAT,SEXE,Féminin,Ensemble,0.0,4.0,168.0,4.0,...,0.0,43.0,0.0,0.0,0.0,4.0,0.0,1152.0,948.0,1782.0
1,200000172,2021,NAT,SEXE,Masculin,Ensemble,0.0,31.0,175.0,4.0,...,0.0,45.0,4.0,0.0,0.0,4.0,0.0,1230.0,841.0,1761.0
2,200000438,2021,NAT,SEXE,Féminin,Ensemble,0.0,4.0,4.0,4.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,139.0,170.0,273.0
3,200000438,2021,NAT,SEXE,Masculin,Ensemble,4.0,0.0,4.0,4.0,...,0.0,4.0,4.0,0.0,0.0,4.0,0.0,171.0,127.0,255.0
4,200000545,2021,NAT,SEXE,Féminin,Ensemble,0.0,0.0,181.0,4.0,...,0.0,19.0,0.0,0.0,0.0,17.0,0.0,1134.0,690.0,1509.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2443,246100663,2021,NAT,SEXE,Masculin,Ensemble,75.0,4.0,132.0,22.0,...,0.0,31.0,0.0,0.0,0.0,53.0,0.0,1508.0,776.0,1996.0
2444,247600588,2021,NAT,SEXE,Féminin,Ensemble,0.0,0.0,8.0,8.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,133.0,145.0,239.0
2445,247600588,2021,NAT,SEXE,Masculin,Ensemble,0.0,0.0,8.0,4.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,113.0,124.0,192.0
2446,248400251,2021,NAT,SEXE,Féminin,Ensemble,34.0,8.0,2248.0,200.0,...,0.0,164.0,24.0,0.0,0.0,8.0,4.0,9533.0,6698.0,13933.0
2447,248400251,2021,NAT,SEXE,Masculin,Ensemble,111.0,32.0,1900.0,104.0,...,0.0,153.0,19.0,0.0,0.0,8.0,0.0,9318.0,6243.0,13235.0

## Lire NAT2 et SEXE et AGER par exemple

In [114]:
nat_epci_file = datapath+'niveau2\\'+"AGER_SEXE_NAT_EPCI"+suffix
#nat_epci_file = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\NAT_EPCI_2026.01.22.csv"
#"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\2026.01.22\EPCI\niveau2\AGER_SEXE_NAT_EPCI_2026.01.22.csv"

demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)

#unit == '248500191' and  
demo01 = demographie_etrangers.query("not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', 'SEXE', 'AGER'], columns='NAT2', values='total_s')
demo02 = demographie_etrangers.query(" (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM', 'SEXE', 'AGER'], columns='NAT2', values='total_s',aggfunc="max") 
demo03 = demographie_etrangers.query(" (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM', 'SEXE', 'AGER'], columns='NAT2', values='total_s',aggfunc="sum") 


frames = [demo01, demo02, demo03]

result = pd.concat(frames)
result.fillna(0, inplace=True)
result.rename_axis(columns=None, inplace=True)
result.reset_index(inplace=True)

# print(result.columns)
# print(result.shape) #(1224, 6)

# print(result)
database = result
#demographie_etrangers.query("unit == '248500191'").NAT2.unique().tolist() à la place liste_natio
database = result.melt(id_vars=['unit', 'NOM', 'SEXE', 'AGER'], value_vars=liste_natio+nationalites_speciales, var_name=['NAT2'], value_name='total_s')
database = database.astype(dtype = {'unit': 'string', 'NOM': 'string', 'NAT2': 'string', 'total_s': 'int'})
#database.rename(columns={'total_s':'SEXE_NAT2'}, inplace=True)

# print(database.shape) #(243576, 4)
# print(database.columns) #['unit', 'NOM', 'NAT2', 'POPULATION_NAT2']
# print(database.dtypes)


database = database.pivot(index=['unit', 'NOM', 'NAT2'], columns=['SEXE', 'AGER'], values='total_s')
#database.rename_axis(columns=None, inplace=True)
#database.reset_index(inplace=True)
print(database.shape) #(243576, 5) 
print(database.columns) #['unit', 'NOM', 'NAT2', 'Féminin', 'Masculin'] 
print(database.dtypes)


modalites_variables = database.columns[3:].tolist()
print(modalites_variables)


#database

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_47832\4099923476.py:5: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')

(243576, 10)
MultiIndex([( 'Féminin',     '0 à 14 ans'),
            ( 'Féminin',    '15 à 29 ans'),
            ( 'Féminin',    '30 à 59 ans'),
            ( 'Féminin',    '60 à 74 ans'),
            ( 'Féminin', '75 ans ou plus'),
            ('Masculin',     '0 à 14 ans'),
            ('Masculin',    '15 à 29 ans'),
            ('Masculin',    '30 à 59 ans'),
            ('Masculin',    '60 à 74 ans'),
            ('Masculin', '75 ans ou plus')],
           names=['SEXE', 'AGER'])
SEXE      AGER
Féminin   0 à 14 ans        int32
          15 à 29 ans       int32
          30 à 59 ans       int32
          60 à 74 ans       int32
          75 ans ou plus    int32
Masculin  0 à 14 ans        int32
          15 à 29 ans       int32
          30 à 59 ans       int32
          60 à 74 ans       int32
          75 ans ou plus    int32
dtype: object
[('Féminin', '60 à 74 ans'), ('Féminin', '75 ans ou plus'), ('Masculin', '0 à 14 ans'), ('Masculin', '15 à 29 ans'), ('Masculin', '30 à 59 ans'), ('Masculin', '60 à 74 ans'), ('Masculin', '75 ans ou plus')]

### version 2 en large

In [ ]:
nat_epci_file = datapath+'niveau2\\'+"AGER_SEXE_NAT_EPCI"+suffix
#nat_epci_file = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\NAT_EPCI_2026.01.22.csv"
#"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\2026.01.22\EPCI\niveau2\AGER_SEXE_NAT_EPCI_2026.01.22.csv"

demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)

#unit == '248500191' and  
demo01 = demographie_etrangers.query("not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', 'SEXE', 'AGER'], columns='NAT2', values='total_s')
demo02 = demographie_etrangers.query(" (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM', 'SEXE', 'AGER'], columns='NAT2', values='total_s',aggfunc="max") 
demo03 = demographie_etrangers.query(" (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM', 'SEXE', 'AGER'], columns='NAT2', values='total_s',aggfunc="sum") 


frames = [demo01, demo02, demo03]

result = pd.concat(frames)
result.fillna(0, inplace=True)
result.rename_axis(columns=None, inplace=True)
result.reset_index(inplace=True)

result #12240 rows × 203 columns

database_wide = result[['unit']]
database_wide['anneeRp'] =  2021
database_wide['indicateur'] =  'AGER_SEXE_NAT_EPCI' #servira de PK avec unit, et anneeRp et permettra de faire le lien avec les autres indicateurs
database_wide['indicateurCode'] =  'AGER_SEXE' 
database_wide['indicateurMode'] =  result[['SEXE', 'AGER']].apply(lambda x: '_'.join(x), axis=1)
database_wide['categorie'] = 'Ensemble' #	Etrangers, Français par acquisition,  SecondeGénération, Immigrés	

# result.drop(columns=['NOM', 'SEXE', 'AGER'], inplace=True)
result['indicateurMode']=  result[['SEXE', 'AGER']].apply(lambda x: '_'.join(x), axis=1)
database_wide = pd.merge(database_wide, result, on=['unit', 'indicateurMode'], how='left') 
database_wide.drop(columns=['NOM', 'SEXE', 'AGER'], inplace=True)
print(database_wide.shape) #12240 rows × 205 columns  

database_wide

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\1433881697.py:5: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')

(12240, 205)

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\1433881697.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['anneeRp'] =  2021
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\1433881697.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['indicateur'] =  'AGER_SEXE_NAT_EPCI' #servira de PK avec unit, et anneeRp et permettra de faire le lien avec les autres indicateurs
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\1433881697.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['indicateurCode'] =  'AGER_SEXE'
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\1433881697.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['indicateurMode'] =  result[['SEXE', 'AGER']].apply(lambda x: '_'.join(x), axis=1)
C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\1433881697.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  database_wide['categorie'] = 'Ensemble' #	Etrangers, Français par acquisition,  SecondeGénération, Immigrés

,unit,anneeRp,indicateur,indicateurCode,indicateurMode,categorie,Afghans,Albanais,Algériens,Allemands,...,Vanuatuans,Vietnamiens,Vénézuéliens,Yéménites,Zambiens,Zaïrois,Zimbabwéens,etrangers,francaisParAcquisition,immigres
0,200000172,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Féminin_0 à 14 ans,Ensemble,0.0,4.0,17.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,133.0,4.0,54.0
1,200000172,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Féminin_15 à 29 ans,Ensemble,0.0,4.0,4.0,0.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,120.0,106.0,151.0
2,200000172,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Féminin_30 à 59 ans,Ensemble,0.0,4.0,103.0,4.0,...,0.0,27.0,0.0,0.0,0.0,4.0,0.0,597.0,554.0,1032.0
3,200000172,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Féminin_60 à 74 ans,Ensemble,0.0,4.0,23.0,4.0,...,0.0,4.0,0.0,0.0,0.0,4.0,0.0,218.0,187.0,386.0
4,200000172,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Féminin_75 ans ou plus,Ensemble,0.0,0.0,4.0,4.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,84.0,89.0,160.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12235,248400251,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Masculin_0 à 14 ans,Ensemble,31.0,4.0,228.0,8.0,...,0.0,4.0,4.0,0.0,0.0,0.0,0.0,1864.0,200.0,744.0
12236,248400251,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Masculin_15 à 29 ans,Ensemble,42.0,8.0,217.0,8.0,...,0.0,8.0,4.0,0.0,0.0,4.0,0.0,1463.0,755.0,1817.0
12237,248400251,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Masculin_30 à 59 ans,Ensemble,36.0,8.0,965.0,31.0,...,0.0,73.0,4.0,0.0,0.0,8.0,0.0,4094.0,3306.0,6968.0
12238,248400251,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Masculin_60 à 74 ans,Ensemble,0.0,0.0,313.0,21.0,...,0.0,40.0,0.0,0.0,0.0,0.0,0.0,1314.0,1428.0,2643.0
12239,248400251,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Masculin_75 ans ou plus,Ensemble,4.0,0.0,171.0,8.0,...,0.0,8.0,0.0,0.0,0.0,0.0,0.0,583.0,554.0,1064.0

In [14]:
result.loc[result.unit == '248500191', ['unit', 'NOM', 'SEXE', 'AGER',  'Tous', 'Français', 'etrangers'] ]

,unit,NOM,SEXE,AGER,Tous,Français,etrangers
11610,248500191,CC de l'Île de Noirmoutier,Féminin,0 à 14 ans,397.0,394.0,4.0
11611,248500191,CC de l'Île de Noirmoutier,Féminin,15 à 29 ans,442.0,436.0,4.0
11612,248500191,CC de l'Île de Noirmoutier,Féminin,30 à 59 ans,1509.0,1474.0,21.0
11613,248500191,CC de l'Île de Noirmoutier,Féminin,60 à 74 ans,1427.0,1401.0,4.0
11614,248500191,CC de l'Île de Noirmoutier,Féminin,75 ans ou plus,1095.0,1083.0,4.0
11615,248500191,CC de l'Île de Noirmoutier,Masculin,0 à 14 ans,460.0,456.0,4.0
11616,248500191,CC de l'Île de Noirmoutier,Masculin,15 à 29 ans,488.0,482.0,4.0
11617,248500191,CC de l'Île de Noirmoutier,Masculin,30 à 59 ans,1384.0,1351.0,21.0
11618,248500191,CC de l'Île de Noirmoutier,Masculin,60 à 74 ans,1254.0,1236.0,4.0
11619,248500191,CC de l'Île de Noirmoutier,Masculin,75 ans ou plus,763.0,755.0,4.0

In [16]:
result[['SEXE', 'AGER']].apply(lambda x: '_'.join(x), axis=1)

0             Féminin_0 à 14 ans
1            Féminin_15 à 29 ans
2            Féminin_30 à 59 ans
3            Féminin_60 à 74 ans
4         Féminin_75 ans ou plus
                  ...
12235        Masculin_0 à 14 ans
12236       Masculin_15 à 29 ans
12237       Masculin_30 à 59 ans
12238       Masculin_60 à 74 ans
12239    Masculin_75 ans ou plus
Length: 12240, dtype: object

In [20]:
database_wide.loc[database_wide.unit == '248500191', ['unit', 'anneeRp', 'indicateur', 'indicateurCode', 'indicateurMode', 'categorie', 'Tous', 'Français', 'etrangers'] ]

,unit,anneeRp,indicateur,indicateurCode,indicateurMode,categorie,Tous,Français,etrangers
11610,248500191,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Féminin_0 à 14 ans,Ensemble,397.0,394.0,4.0
11611,248500191,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Féminin_15 à 29 ans,Ensemble,442.0,436.0,4.0
11612,248500191,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Féminin_30 à 59 ans,Ensemble,1509.0,1474.0,21.0
11613,248500191,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Féminin_60 à 74 ans,Ensemble,1427.0,1401.0,4.0
11614,248500191,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Féminin_75 ans ou plus,Ensemble,1095.0,1083.0,4.0
11615,248500191,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Masculin_0 à 14 ans,Ensemble,460.0,456.0,4.0
11616,248500191,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Masculin_15 à 29 ans,Ensemble,488.0,482.0,4.0
11617,248500191,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Masculin_30 à 59 ans,Ensemble,1384.0,1351.0,21.0
11618,248500191,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Masculin_60 à 74 ans,Ensemble,1254.0,1236.0,4.0
11619,248500191,2021,AGER_SEXE_NAT_EPCI,AGER_SEXE,Masculin_75 ans ou plus,Ensemble,763.0,755.0,4.0

In [ ]:
import pandas.io.sql as sql
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:postgres@localhost:5432/inseedb')
ORM_conn=engine.connect()
#ORM_conn

#result.to_postgis('NAT', con=ORM_conn , schema='imhana2021', if_exists='replace', index=False)
database_wide.to_sql('RP_EPCI_wide', con=ORM_conn , schema='imhana2021', if_exists='append', index=False)

ORM_conn.commit()
ORM_conn.close()

In [ ]:
result.SEXE.unique() #['Féminin' 'Masculin']
result.AGER.unique() #['15-24 ans' '25-39 ans' '40-64 ans' '65 ans ou plus']
indicateurMode = []
for i in result.SEXE.unique():
    for j in result.AGER.unique():
        indicateurMode.append(i + '_' + j)
indicateurMode

ValueError: operands could not be broadcast together with shapes (2,) (5,)

In [115]:
def tuple_to_csv(tpl):
    if isinstance(tpl, tuple):
        return "_".join(map(str, tpl))
    else:
        return tpl

database.columns.map(tuple_to_csv)
database.columns = database.columns.map(tuple_to_csv)
database.rename_axis(columns=None, inplace=True)
database.reset_index(inplace=True)
database

,unit,NOM,NAT2,Féminin_0 à 14 ans,Féminin_15 à 29 ans,Féminin_30 à 59 ans,Féminin_60 à 74 ans,Féminin_75 ans ou plus,Masculin_0 à 14 ans,Masculin_15 à 29 ans,Masculin_30 à 59 ans,Masculin_60 à 74 ans,Masculin_75 ans ou plus
0,200000172,CC Faucigny-Glières,Afghans,0,0,0,0,0,0,0,0,0,0
1,200000172,CC Faucigny-Glières,Albanais,4,4,4,4,0,4,4,16,4,0
2,200000172,CC Faucigny-Glières,Algériens,17,4,103,23,4,16,38,82,29,4
3,200000172,CC Faucigny-Glières,Allemands,0,0,4,4,4,4,4,4,4,4
4,200000172,CC Faucigny-Glières,Américains (U.S.),0,0,4,4,4,4,0,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
243571,249500513,CC du Vexin-Val de Seine,Zaïrois,0,4,4,4,0,4,4,4,0,0
243572,249500513,CC du Vexin-Val de Seine,Zimbabwéens,0,0,0,0,0,0,0,0,0,0
243573,249500513,CC du Vexin-Val de Seine,etrangers,42,30,144,65,32,38,36,209,72,30
243574,249500513,CC du Vexin-Val de Seine,francaisParAcquisition,4,31,189,66,27,4,26,144,75,29
243575,249500513,CC du Vexin-Val de Seine,immigres,4,45,294,121,48,4,47,303,134,54

## Préparer la sauvegarde des indicateurs avec les libellés des modalités

In [45]:
#modalites_variables = database.columns[3:].tolist()
#modalites_variables.split('_')[0] #pour vérifier que ça fonctionne
modalites_variables = database_wide.indicateurMode.unique() #['Féminin_15-24 ans' 'Féminin_25-39 ans' 'Féminin_40-64 ans' 'Féminin_65 ans ou plus' 'Masculin_15-24 ans' 'Masculin_25-39 ans' 'Masculin_40-64 ans' 'Masculin_65 ans ou plus']

df = pd.DataFrame({'indicateur' : 'SEXE_AGER', 'modalites': modalites_variables})
df['code01'] = df.indicateur.apply(lambda x: x.split('_')[0])
df['modalite01'] = df.modalites.apply(lambda x: x.split('_')[0])

df['code02'] = df.indicateur.apply(lambda x: x.split('_')[1])
df['modalite02'] = df.modalites.apply(lambda x: x.split('_')[1])


df
#'Féminin_75 ans ou plus'.split('_')

  indicateur                modalites code01 modalite01 code02      modalite02
0  SEXE_AGER       Féminin_0 à 14 ans   SEXE    Féminin   AGER      0 à 14 ans
1  SEXE_AGER      Féminin_15 à 29 ans   SEXE    Féminin   AGER     15 à 29 ans
2  SEXE_AGER      Féminin_30 à 59 ans   SEXE    Féminin   AGER     30 à 59 ans
3  SEXE_AGER      Féminin_60 à 74 ans   SEXE    Féminin   AGER     60 à 74 ans
4  SEXE_AGER   Féminin_75 ans ou plus   SEXE    Féminin   AGER  75 ans ou plus
5  SEXE_AGER      Masculin_0 à 14 ans   SEXE   Masculin   AGER      0 à 14 ans
6  SEXE_AGER     Masculin_15 à 29 ans   SEXE   Masculin   AGER     15 à 29 ans
7  SEXE_AGER     Masculin_30 à 59 ans   SEXE   Masculin   AGER     30 à 59 ans
8  SEXE_AGER     Masculin_60 à 74 ans   SEXE   Masculin   AGER     60 à 74 ans
9  SEXE_AGER  Masculin_75 ans ou plus   SEXE   Masculin   AGER  75 ans ou plus

In [ ]:
    #Lire C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\Dico_variables_RP_v2.xlsx
dico_variables_file = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\Dico_variables_RP_v2.xlsx"
dico_variables = pd.read_excel(dico_variables_file, sheet_name='RP_individus_principale', skiprows=3)
#.to_sql('dico_variables_rp', con=create_engine('postgresql://postgres:postgres@localhost:5432/inseedb') , schema=schema_name, if_exists='replace', index=False)
dico_variables [['Nom de la variable', 'Libellé', 'Modalités']]

dico_variables [['Nom de la variable', 'Libellé']]

dico_variables.loc[dico_variables['Nom de la variable'].str.startswith('NAT'), ['Nom de la variable', 'Libellé', 'Modalités']]

,Nom de la variable,Libellé,Modalités
179,NAT,Nationalité actuelle,4 - Afghanistan
180,NAT2,Nationalité recodée à partir de la nationalité...,NaN
181,NAT3,Nationalité recodée à partir de la nationalité...,NaN
182,NAT13,Nationalité actuelle en 13 postes,0 - Français de naissance
183,NATC,Nationalité actuelle condensée,0 - Français de naissance
184,NATN,Nationalité à la naissance des Français,4 - Afghanistan
185,NATN12,Nationalité à la naissance des Français en 12 ...,1 - Français de naissance
186,NATNC,Nationalité à la naissance des Français condensée,1 - Français de naissance
187,NATR,Nationalité actuelle regroupée,12 - Algériens

In [42]:
# Sauvegarder le dictionnaire de variables en base de données

engine = create_engine('postgresql://postgres:postgres@localhost:5432/inseedb')
dico_variables [['Nom de la variable', 'Libellé', 'Modalités']].to_sql('dico_variables_rp', con=engine , schema='imhana2021', if_exists='replace', index=False)
engine.dispose()

In [43]:
df = pd.DataFrame({'indicateur' : 'NAT2', 'modalites': ['']})
df.modalites.apply(lambda x: x.split('_')[0])
df['code01'] = df.indicateur.apply(lambda x: x.split('_')[0])
df['modalite01'] = df.modalites.apply(lambda x: x.split('_')[0])
df

print(dico_variables.shape) #237, 232
indicateurs = pd.merge(df, dico_variables [['Nom de la variable', 'Libellé']], left_on='code01', right_on='Nom de la variable', how='inner')
indicateurs.rename(columns={'Libellé':'libelle01'}, inplace=True)
indicateurs.drop(columns=['Nom de la variable'], inplace=True)
indicateurs

(239, 232)

,indicateur,modalites,code01,modalite01,libelle01
0,NAT2,,NAT2,,Nationalité recodée à partir de la nationalité...

In [ ]:
# Sauvegarder le dictionnaire des indicateurs exportés en base de données
# Pour la première fois 

engine = create_engine('postgresql://postgres:postgres@localhost:5432/inseedb')
indicateurs.to_sql('indicateurs', con=engine , schema='imhana2021', if_exists='replace', index=False)
engine.dispose()

In [46]:
indicateurs = pd.merge(df, dico_variables [['Nom de la variable', 'Libellé']], left_on='code01', right_on='Nom de la variable', how='inner')
#[['code01', 'Libellé', 'modalite01']]
indicateurs.rename(columns={'Libellé':'libelle01'}, inplace=True)
indicateurs.drop(columns=['Nom de la variable'], inplace=True)
indicateurs
indicateurs = pd.merge(indicateurs, dico_variables [['Nom de la variable', 'Libellé']], left_on='code02', right_on='Nom de la variable', how='inner')
indicateurs.rename(columns={'Libellé':'libelle02'}, inplace=True)
indicateurs.drop(columns=['Nom de la variable'], inplace=True)
indicateurs

,indicateur,modalites,code01,modalite01,code02,modalite02,libelle01,libelle02
0,SEXE_AGER,Féminin_0 à 14 ans,SEXE,Féminin,AGER,0 à 14 ans,Sexe,Âge en différence de millésimes regroupé en 5 ...
1,SEXE_AGER,Féminin_15 à 29 ans,SEXE,Féminin,AGER,15 à 29 ans,Sexe,Âge en différence de millésimes regroupé en 5 ...
2,SEXE_AGER,Féminin_30 à 59 ans,SEXE,Féminin,AGER,30 à 59 ans,Sexe,Âge en différence de millésimes regroupé en 5 ...
3,SEXE_AGER,Féminin_60 à 74 ans,SEXE,Féminin,AGER,60 à 74 ans,Sexe,Âge en différence de millésimes regroupé en 5 ...
4,SEXE_AGER,Féminin_75 ans ou plus,SEXE,Féminin,AGER,75 ans ou plus,Sexe,Âge en différence de millésimes regroupé en 5 ...
5,SEXE_AGER,Masculin_0 à 14 ans,SEXE,Masculin,AGER,0 à 14 ans,Sexe,Âge en différence de millésimes regroupé en 5 ...
6,SEXE_AGER,Masculin_15 à 29 ans,SEXE,Masculin,AGER,15 à 29 ans,Sexe,Âge en différence de millésimes regroupé en 5 ...
7,SEXE_AGER,Masculin_30 à 59 ans,SEXE,Masculin,AGER,30 à 59 ans,Sexe,Âge en différence de millésimes regroupé en 5 ...
8,SEXE_AGER,Masculin_60 à 74 ans,SEXE,Masculin,AGER,60 à 74 ans,Sexe,Âge en différence de millésimes regroupé en 5 ...
9,SEXE_AGER,Masculin_75 ans ou plus,SEXE,Masculin,AGER,75 ans ou plus,Sexe,Âge en différence de millésimes regroupé en 5 ...

In [48]:

engine = create_engine('postgresql://postgres:postgres@localhost:5432/inseedb')
indicateurs.to_sql('indicateurs', con=engine , schema='imhana2021', if_exists='append', index=False)
engine.dispose()

# Lire les données de logement

In [ ]:

datapath = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\logement\\"
variable = 'TYPL'

nat_epci_file = datapath+variable+"_NAT"+epcisuffix
#nat_epci_file = r"C:\Travail\MIGRINTER\Labo\IMHANA\Méthodologie\Statistiques\export_CASD_ergonomiques\\2026.01.22\EPCI\NAT_EPCI_2026.01.22.csv"

demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')
demographie_etrangers['unit'] = demographie_etrangers['unit'].astype(str)

#unit == '248500191' and  
demo01 = demographie_etrangers.query(" not(unit in @EPCI_fictives) and not(unit in @doublons_CC_EPCI) and not(unit in @doublons_CA_CU_EPCI) ").pivot(index=['unit', 'NOM', variable], columns='NAT2', values='total_s')
demo02 = demographie_etrangers.query(" (unit in @doublons_CC_EPCI) ").pivot_table(index=['unit', 'NOM', variable], columns='NAT2', values='total_s',aggfunc="max") 
demo03 = demographie_etrangers.query(" (unit in @doublons_CA_CU_EPCI) ").pivot_table(index=['unit', 'NOM', variable], columns='NAT2', values='total_s',aggfunc="sum") 


frames = [demo01, demo02, demo03]

result = pd.concat(frames)
result.fillna(0, inplace=True)
result.rename_axis(columns=None, inplace=True)
result.reset_index(inplace=True)

print(result.columns)
print(result.shape) #(1224, 6)


result
database_wide = result[['unit']]
database_wide['anneeRp'] =  2021
database_wide['indicateur'] =  variable #servira de PK avec unit, et anneeRp et permettra de faire le lien avec les autres indicateurs
database_wide['indicateurCode'] =  variable 
database_wide['indicateurMode'] =  result[[variable]]
database_wide['categorie'] = 'Ensemble' #	Etrangers, Français par acquisition,  SecondeGénération, Immigrés	

result['indicateurMode']=  result[[variable]]
database_wide = pd.merge(database_wide, result, on=['unit', 'indicateurMode'], how='left') 
database_wide.drop(columns=['NOM', variable], inplace=True)
print(database_wide.shape)
#(6859, 203) avec les 4 colonnes de unit, anneeRp, indicateur, indicateurCode, indicateurMode, categorie, et les 197 colonnes de nationalités, 'Tous' puis 'etrangers', 'francaisParAcquisition', 'immigres')

database_wide

C:\Users\cplumeje\AppData\Local\Temp\ipykernel_22336\2338341961.py:7: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  demographie_etrangers = pd.read_csv(nat_epci_file, sep=';', encoding='latin1')

Index(['unit', 'NOM', 'TYPL', 'Afghans', 'Albanais', 'Algériens', 'Allemands',
       'Américains (U.S.)', 'Andorrans', 'Angolais',
       ...
       'Vanuatuans', 'Vietnamiens', 'Vénézuéliens', 'Yéménites', 'Zambiens',
       'Zaïrois', 'Zimbabwéens', 'etrangers', 'francaisParAcquisition',
       'immigres'],
      dtype='object', length=200)
(6859, 200)
(6859, 203)

,unit,anneeRp,indicateur,indicateurCode,indicateurMode,categorie,Afghans,Albanais,Algériens,Allemands,...,Vanuatuans,Vietnamiens,Vénézuéliens,Yéménites,Zambiens,Zaïrois,Zimbabwéens,etrangers,francaisParAcquisition,immigres
0,200000172,2021,TYPL,TYPL,Appartement,Ensemble,0.0,4.0,107.0,4.0,...,0.0,37.0,0.0,0.0,0.0,0.0,0.0,702.0,517.0,1136.0
1,200000172,2021,TYPL,TYPL,Logement-foyer,Ensemble,0.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,4.0
2,200000172,2021,TYPL,TYPL,Maison,Ensemble,0.0,4.0,31.0,4.0,...,0.0,4.0,4.0,0.0,0.0,4.0,0.0,354.0,381.0,634.0
3,200000172,2021,TYPL,TYPL,Pièce indépendante (ayant sa propre entrée),Ensemble,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,4.0
4,200000438,2021,TYPL,TYPL,Appartement,Ensemble,0.0,0.0,4.0,4.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,28.0,4.0,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6854,248400251,2021,TYPL,TYPL,Chambre d'hôtel,Ensemble,4.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.0,4.0,27.0
6855,248400251,2021,TYPL,TYPL,Habitation de fortune,Ensemble,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,8.0,8.0
6856,248400251,2021,TYPL,TYPL,Logement-foyer,Ensemble,4.0,0.0,4.0,8.0,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,102.0,20.0,116.0
6857,248400251,2021,TYPL,TYPL,Maison,Ensemble,21.0,8.0,470.0,99.0,...,0.0,78.0,8.0,0.0,0.0,8.0,0.0,1732.0,2992.0,4253.0
6858,248400251,2021,TYPL,TYPL,Pièce indépendante (ayant sa propre entrée),Ensemble,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,22.0,34.0

epci = dataW.groupby('siren_epci2022').sum(numeric_only=True)
epci = epci.reset_index(drop=False);# siren_epci2022 colonne
epci.rename(columns={"siren_epci2022": "code"}, inplace=True)
epci['level'] =  'epci';
print(epci.shape)